medInria/medInria-public

- src-plugins/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
- src-plugins/medVtkView/medVtkViewNavigator.cpp
- src/medCore/parameters/medAbstractParameter.cpp
- src/medCore/parameters/medAbstractParameter.h
- src/medCore/parameters/medBoolGroupParameter.cpp
- src/medCore/parameters/medBoolGroupParameter.h
- src/medCore/parameters/medCompositeParameter.cpp
- src/medCore/parameters/medCompositeParameter.h
- src/medCore/parameters/medDataListParameter.cpp
- src/medCore/parameters/medDataListParameter.h
- src/medCore/parameters/medTimeLineParameter.cpp
- src/medCore/parameters/medTimeLineParameter.h
- src/medCore/views/medAbstractImageView.cpp
> Image reset in MPR mode

- src-plugins/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
- src-plugins/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h
- src-plugins/medVtkView/medVtkViewNavigator.cpp
- src-plugins/vtkDataMesh/interactors/vtkDataMesh4DInteractor.cpp
- src/medCore/parameters/medDoubleParameter.cpp
- src/medCore/parameters/medDoubleParameter.h
- src/medVtkInria/vtkImageView/vtkImageView.cxx
- src/medVtkInria/vtkImageView/vtkImageView2DCommand.cxx
We had some comments here that window/level was not really handy to manage intensity and that min and max could be more useful.
Here is a version of it.
You can still change window/level with the mouse but you can also set min and max with sliders in the toolbox.
Tell me what you think.
Guillaume
> Changing window/level to min/max

- RELEASE_NOTES.txt
- src-plugins/medVtkView/medVtkView.cpp
- src-plugins/vtkDataMesh/navigators/vtkDataMeshNavigator.cpp
Since this is a pretty trivial change, and actually put things back to how they were before the view refactoring, I'm thinking we add it to the release ? This also updates the release notes.
> Fixes depth peeling not working on all platforms

- src-plugins/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
- src/medVtkInria/vtkVisuManagement/vtkLookupTableManager.cxx
- src/medVtkInria/vtkVisuManagement/vtkLookupTableManager.h
- src/medVtkInria/vtkVisuManagement/vtkTransferFunctionPresets.cxx
- src/medVtkInria/vtkVisuManagement/vtkTransferFunctionPresets.h
A tentative binary map LUT to better see label images. Tell me what you think.
PS : by the way, this made us realize (me and RP) the LUT/transfer functions system in medinria is quite a bit crappy. @papadop : any chance your branch on that could be revived / finished soon ?
> Add a colormap for images that are label maps

- app/medInria/medDiffusionWorkspace.h
- app/medInria/medFilteringWorkspace.h
- app/medInria/medHomepageArea.cpp
- app/medInria/medRegistrationWorkspace.h
- app/medInria/medSegmentationWorkspace.h
- app/medInria/medVisualizationWorkspace.h
- src/medCore/gui/factories/medWorkspaceFactory.cpp
- src/medCore/gui/factories/medWorkspaceFactory.h
- src/medCore/gui/medAbstractWorkspace.h
I added a category to workspaces so that they can be organised on the home page. I also created columns for different categories on the home page.
Workspaces in private repos will have to be updated accordingly.
> Categorise workspaces and clean up home page

- CMakeLists.txt
- app/medInria/CMakeLists.txt
- app/medPluginGenerator/CMakeLists.txt
- src-plugins/legacy/medVtkView/CMakeLists.txt
- src-plugins/process/arithmetic_operation/medItkAddImageProcess/CMakeLists.txt
- src-plugins/process/arithmetic_operation/medItkDivideImageProcess/CMakeLists.txt
- src-plugins/process/arithmetic_operation/medItkMultiplyImageProcess/CMakeLists.txt
- src-plugins/process/arithmetic_operation/medItkSubtractImageProcess/CMakeLists.txt
- src-plugins/process/morphomath_operation/medItkClosingImageProcess/CMakeLists.txt
- src-plugins/process/morphomath_operation/medItkDilateImageProcess/CMakeLists.txt
- src-plugins/process/morphomath_operation/medItkErodeImageProcess/CMakeLists.txt
- src-plugins/process/morphomath_operation/medItkOpeningImageProcess/CMakeLists.txt
- src/medCore/CMakeLists.txt
- src/medCoreLegacy/CMakeLists.txt
Use the AUTORCC tool provided by CMake to generate Qt resources files.
> CMake use AUTORCC.

- src-plugins/process/arithmetic_operation/medItkAddImageProcess/CMakeLists.txt
- src-plugins/process/arithmetic_operation/medItkDivideImageProcess/CMakeLists.txt
- src-plugins/process/arithmetic_operation/medItkMultiplyImageProcess/CMakeLists.txt
- src-plugins/process/arithmetic_operation/medItkSubtractImageProcess/CMakeLists.txt
- src-plugins/process/morphomath_operation/medItkClosingImageProcess/CMakeLists.txt
- src-plugins/process/morphomath_operation/medItkDilateImageProcess/CMakeLists.txt
- src-plugins/process/morphomath_operation/medItkErodeImageProcess/CMakeLists.txt
- src-plugins/process/morphomath_operation/medItkOpeningImageProcess/CMakeLists.txt
Use the MODULE CMake Keyword in add_library([...]) to produce lib having to be dynamically loaded (plugins).
see: http://www.cmake.org/cmake/help/v3.0/command/add_library.html
> MODULE CMake Keyword

- src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
Propagates Loic's correction to spurious data saving when using the non persistent database
> Prevents disk writing when saving non persistent data from process

- README.md
minor change to make the GitHub welcome page sexier
> Fix markdown syntax of the README.md

- src/layers/legacy/medCoreLegacy/views/navigators/medAbstractImageViewNavigator.cpp
- src/layers/legacy/medImageIO/vtkItkConversion.tpp
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImage4DInteractor.cpp
Correction of bad behavior in handling of time for 4D data.
(Correction of issues #292 4D views time changing is wrong (compared to medinria 2 which works fine) )
> 4 d time handling correction

- src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Correction of We've "lost the about plugins buttons. We should put them back" by mikejbuckingham
> About plugin

- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkVectorFieldInteractor.cpp
- src/plugins/legacy/itkDataImage/manager/vtkVectorVisuManager.cxx
- src/plugins/legacy/medVtkView/medVtkViewNavigator.cpp
Solves #322
Correction of bug on glyph
> Solved #322

- src/app/medInria/main.cpp
- src/layers/legacy/medVtkInria/vtkVisuManagement/vtkLookupTableManager.cxx
- src/layers/legacy/medVtkInria/vtkVisuManagement/vtkLookupTableManager.h
- src/plugins/legacy/medVtkFibersData/interactors/medVtkFibersDataInteractor.cpp
- src/plugins/legacy/medVtkFibersData/interactors/medVtkFibersDataInteractor.h
- src/plugins/legacy/medVtkFibersData/manager/vtkFibersManager.cxx
- src/plugins/legacy/medVtkFibersData/manager/vtkFibersManager.h
- src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
> LUT and WindowLevel rang for fibers

- src/plugins/legacy/medVtkFibersData/interactors/medVtkFibersDataInteractor.cpp
- src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
- src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.h
Inspired by "Mesh scalar range editor" #186 pull-request
> Data mesh min max

- src/layers/legacy/medCoreLegacy/parameters/medCompositeParameterL.cpp
Fix "Crash when linking views" #327
> Fix "Crash when linking views" #327

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2DCommand.cxx
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h
1st step for "Interactor option for itkDataImage to switch between interpolation modes (nearest / linear)" into #330
> 1st step for interpolation button

- superbuild/CMakeLists.txt
- superbuild/ConfigureExternalProjects.cmake
- superbuild/environment/CheckEnvironment.cmake
- superbuild/environment/GitlabInriaSshTest.cmake
- superbuild/projects_modules/dtk.cmake
- superbuild/projects_modules/dtkImaging.cmake
Adaptation of cmake files for the new repository of dtk.
DTK repository is now on gitlab of Inria.
> Dtk new repo

- src/plugins/legacy/itkDataSHImage/itkDataSHImagePlugin.cpp
Same as https://github.com/medInria/medInria-visages/pull/16 ;-)
> Hyperlink DOIs to preferred resolver

- src/plugins/process/arithmetic_operation/medItkAddImageProcess.cpp
- src/plugins/process/arithmetic_operation/medItkAddImageProcess.h
- src/plugins/process/arithmetic_operation/medItkDivideImageProcess.cpp
- src/plugins/process/arithmetic_operation/medItkDivideImageProcess.h
- src/plugins/process/arithmetic_operation/medItkMultiplyImageProcess.cpp
- src/plugins/process/arithmetic_operation/medItkMultiplyImageProcess.h
- src/plugins/process/arithmetic_operation/medItkSubtractImageProcess.cpp
- src/plugins/process/arithmetic_operation/medItkSubtractImageProcess.h
> Correct image arithmetic bug with incompatible image types

- CMakeLists.txt
- src/CMakeLists.txt
- src/plugins/legacy/medCompositeDataSets/CMakeLists.txt
- src/plugins/legacy/undoRedoRegistration/CMakeLists.txt
Unified CMake minimum version needed
> Unified CMake minimum version needed

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageViewCornerAnnotation.cxx
> Buffer overflow

- src/app/medInria/medPluginWidget.cpp
- src/layers/legacy/medCoreLegacy/medPluginLegacy.cpp
- src/layers/legacy/medCoreLegacy/medPluginLegacy.h
- src/plugins/CMakeLists.txt
- src/plugins/legacy/medBinaryOperation/CMakeLists.txt
- src/plugins/legacy/medBinaryOperation/itkAndOperator.cpp
- src/plugins/legacy/medBinaryOperation/itkAndOperator.h
- src/plugins/legacy/medBinaryOperation/itkNotOperator.cpp
- src/plugins/legacy/medBinaryOperation/itkNotOperator.h
- src/plugins/legacy/medBinaryOperation/itkOrOperator.cpp
- src/plugins/legacy/medBinaryOperation/itkOrOperator.h
- src/plugins/legacy/medBinaryOperation/itkXorOperator.cpp
- src/plugins/legacy/medBinaryOperation/itkXorOperator.h
- src/plugins/legacy/medBinaryOperation/medBinaryOperationPlugin.cpp
- src/plugins/legacy/medBinaryOperation/medBinaryOperationPlugin.h
- src/plugins/legacy/medBinaryOperation/medBinaryOperationPlugin.json
- src/plugins/legacy/medBinaryOperation/medBinaryOperationPluginExport.h
- src/plugins/legacy/medBinaryOperation/medBinaryOperationToolBox.cpp
- src/plugins/legacy/medBinaryOperation/medBinaryOperationToolBox.h
- src/plugins/legacy/medBinaryOperation/medBinaryOperatorBase.cpp
- src/plugins/legacy/medBinaryOperation/medBinaryOperatorBase.h
- src/plugins/legacy/medMaskApplication/CMakeLists.txt
- src/plugins/legacy/medMaskApplication/medMaskApplication.cpp
- src/plugins/legacy/medMaskApplication/medMaskApplication.h
- src/plugins/legacy/medMaskApplication/medMaskApplicationPlugin.cpp
- src/plugins/legacy/medMaskApplication/medMaskApplicationPlugin.h
- src/plugins/legacy/medMaskApplication/medMaskApplicationPluginExport.h
- src/plugins/legacy/medMaskApplication/medMaskApplicationToolBox.cpp
- src/plugins/legacy/medMaskApplication/medMaskApplicationToolBox.h
This PR is based on and will be rebased with @Florent2305  Filtering Legacy workspace and with [medMaskApplicationPlugin](https://github.com/medInria/medInria-public/pull/355).
It adds:
* the medBinaryOperator plugin
* `medPluginLegacy.h/.cpp` to avoid redundancies in the creation of plugins
:m:
> [music3] add medBinaryOperator + medPluginLegacy 

- src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
- src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.h
> Please be careful of return type

- src/layers/legacy/medCoreLegacy/gui/toolboxes/medSegmentationSelectorToolBox.cpp
Was done in filtering and registration but not in segmentation.
> [medSegmentationSelectorToolBox] setWorkspace on toolbox

- src/layers/legacy/medCoreLegacy/views/interactors/medAbstractLayeredViewInteractor.cpp
Fixes https://github.com/medInria/medInria-public/issues/239 (Hakim wrote the solution in the issue)
What was the problem:
* Add 2 data, hide one (clicking on the thumbnail in Layer Settings)
* Add a new data -> the hidden data was not hidden anymore
:m:
> [medAbstractLayeredViewInteractor] layer visibility when add a new data

- src/app/medInria/CMakeLists.txt
- src/app/medInria/areas/homepage/medHomepageArea.cpp
- src/app/medInria/areas/homepage/medHomepageArea.h
- src/app/medInria/main.cpp
- src/app/medInria/medApplication.cpp
- src/app/medInria/medApplication.h
- src/app/medInria/medLogger.cpp
- src/app/medInria/medLogger.h
- src/app/medInria/medMainWindow.cpp
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
- src/plugins/legacy/medMaskApplication/medMaskApplicationToolBox.cpp
This PR will be rebased with the others music3 PRs.
Commit: https://github.com/medInria/medInria-public/commit/b0063049d166cee7a73295eae8151125d907b6ab
Fixes https://github.com/Inria-Asclepios/medInria-public/issues/139
Add a log file:
* logs are redirect to the console and to the file
* possibilities: dtkInfo/etc, qDebug/etc, std::cout/cerr
* allow users to send the log file if needed, or to look at it 
* works with the `displayMessageError` from https://github.com/medInria/medInria-public/pull/358
* add a button on homepage to open the logs: https://github.com/medInria/medInria-public/pull/360 was already adapted to this button
:m:
> [music3] add a log file 

- src/layers/legacy/medVtkDataMeshBase/CMakeLists.txt
This problem avoid a good generation on CI/Inria
> Debug medVtkDataMeshBase link problem with VTK.

- src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
- src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.h
- src/layers/legacy/medCoreLegacy/views/medAbstractLayeredView.cpp
- src/layers/legacy/medCoreLegacy/views/medAbstractLayeredView.h
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.h
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
- src/plugins/legacy/medVtkView/CMakeLists.txt
- src/plugins/legacy/medVtkView/medVtkView.cpp
- src/plugins/legacy/medVtkView/medVtkView.h
From https://github.com/Inria-Asclepios/medInria-public/pull/445
Commit: https://github.com/medInria/medInria-public/commit/2f69e62e416f41651ecefdadcc1d28d93262e1c5
> In 3D view, double clicking on a mesh layer will reset the camera focus on that mesh
:m:
> [music3] Reset camera on layer double click

- src/app/medInria/medFileSystemDataSource.cpp
From https://github.com/Inria-Asclepios/medInria-public/pull/511
It allows to save the path chosen by users in Browser -> File System.
:m:
> [music3] in Browser/File System path saved

- src/layers/legacy/medCoreLegacy/views/medAbstractLayeredView.cpp
From https://github.com/Inria-Asclepios/medInria-public/pull/367/files
> - Fix the "Attempt to add twice the same data" warning message.
:m:
> [music3] medAbstractLayeredView - Fix add data twice

- src/app/medInria/medLogger.cpp
Vote for your favorite solution
> done a medlog without filesystem C++17 dependencies

- src/CMakeLists.txt
- src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
- src/layers/legacy/medVtkDataMeshBase/CMakeLists.txt
> Get around for "désynchronisation des vues #347"

- src/layers/legacy/medCoreLegacy/parameters/medBoolGroupParameterL.h
- src/plugins/CMakeLists.txt
- src/plugins/legacy/voiCutter/CMakeLists.txt
- src/plugins/legacy/voiCutter/voiCutterPlugin.cpp
- src/plugins/legacy/voiCutter/voiCutterPlugin.h
- src/plugins/legacy/voiCutter/voiCutterPlugin.json
- src/plugins/legacy/voiCutter/voiCutterPluginExport.h
- src/plugins/legacy/voiCutter/voiCutterToolBox.cpp
- src/plugins/legacy/voiCutter/voiCutterToolBox.h
- src/plugins/legacy/voiCutter/vtkInriaInteractorStyleDrawPolygon.cxx
- src/plugins/legacy/voiCutter/vtkInriaInteractorStyleDrawPolygon.h
This PR adds the VOI Cutter toolbox in Segmentation workspace. The user can manually crop parts of the input volume.
:m:
> [music3] Voi Cutter - add toolbox

- src/app/medInria/medMainWindow.cpp
- src/app/medInria/medSearchToolboxDialog.cpp
- src/app/medInria/medSearchToolboxDialog.h
- src/layers/legacy/medCoreLegacy/gui/database/medDatabaseMetadataItemDialog.cpp
- src/layers/legacy/medCoreLegacy/gui/database/medDatabaseMetadataItemDialog.h
- src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp
- src/layers/legacy/medUtilities/medTransform.h
- src/plugins/CMakeLists.txt
- src/plugins/legacy/medAlgorithmPaint/CMakeLists.txt
- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintPlugin.cpp
- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintPlugin.h
- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintPlugin.json
- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintPluginExport.h
- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.h
- src/plugins/legacy/medAlgorithmPaint/medPaintBrush.cpp
- src/plugins/legacy/medAlgorithmPaint/medPaintBrush.h
- src/plugins/legacy/reformat/CMakeLists.txt
- src/plugins/legacy/reformat/medResliceViewer.cpp
- src/plugins/legacy/reformat/reformatPlugin.cpp
- src/plugins/legacy/reformat/resampleProcess.cpp
- src/plugins/legacy/reformat/resliceToolBox.cpp
- src/plugins/legacy/reformat/resliceToolBox.h
Fixes https://github.com/medInria/medInria-public/issues/394
Based on https://github.com/medInria/medInria-public/pull/425 (will be rebased)
Commit https://github.com/medInria/medInria-public/commit/c5579bfc55f3d69f9b723ef8676c9e91f9ce5482
Change the "msc" files/classes to "med".
:m:
> [Names] change msc to med

- src/layers/legacy/medCoreLegacy/gui/commonWidgets/medComboBox.h
Add a doxygen comment to the medComboBox class.
:m:
> [medComboBox] add a doxygen description

- src/plugins/legacy/itkProcessRegistrationDiffeomorphicDemons/CMakeLists.txt
- src/plugins/legacy/manualRegistration/CMakeLists.txt
- src/plugins/legacy/medAlgorithmPaint/CMakeLists.txt
- src/plugins/legacy/medBinaryOperation/CMakeLists.txt
- src/plugins/legacy/medCreateMeshFromMask/CMakeLists.txt
- src/plugins/legacy/medMaskApplication/CMakeLists.txt
- src/plugins/legacy/medRemeshing/CMakeLists.txt
- src/plugins/legacy/meshManipulation/CMakeLists.txt
- src/plugins/legacy/meshMapping/CMakeLists.txt
- src/plugins/legacy/polygonRoi/CMakeLists.txt
- src/plugins/legacy/reformat/CMakeLists.txt
- src/plugins/legacy/variationalSegmentation/CMakeLists.txt
- src/plugins/legacy/voiCutter/CMakeLists.txt
Add libraries components for ITK and VTK in plugins.
:m:
> [CMakeLists] add required components

- src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.cpp
- src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.h
- src/layers/legacy/medCoreLegacy/gui/lookUpTables/medLUTToXMLWriter.h
- src/layers/legacy/medCoreLegacy/gui/lookUpTables/medLoadLUTDialog.h
- src/layers/legacy/medCoreLegacy/gui/lookUpTables/medSaveLUTDialog.h
- src/layers/legacy/medCoreLegacy/gui/lookUpTables/medXMLToLUTReader.h
- src/plugins/legacy/medCreateMeshFromMask/CMakeLists.txt
- src/plugins/legacy/meshMapping/CMakeLists.txt
- Please be careful to export
- add link libraries into cmake
> OSX and Windows Compilation and Link

- src/plugins/legacy/manualRegistration/CMakeLists.txt
- superbuild/projects_modules/medInria.cmake
- Correction on post compilation for MS-Windows 
- manualRegistration CMake correction
> - Correction on post compilation for MS-Windows

- src/app/medInria/areas/workspaces/filtering/medFilteringWorkspace.cpp
> fix bug "Filtering process creation without process #408"

- src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
Fixes https://github.com/medInria/medInria-public/issues/427
Fixes https://github.com/Inria-Asclepios/medInria-public/issues/581
From https://github.com/Inria-Asclepios/medInria-public/pull/586 by @nebatmusic 
Allow to import non axial dicom in the application.
:m:
> [DICOM] import non axial acquisition

- src/layers/legacy/medCoreLegacy/views/medAbstractImageView.cpp
Fixes https://github.com/medInria/medInria-public/issues/429
Solve the 4-split problem with the slicing parameter. Now the slicing events are only linked to the 3D view.
:m:
> [4-split] bug with the slice parameter

- src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.cxx
- src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx
- src/plugins/CMakeLists.txt
- src/plugins/legacy/iterativeClosestPoint/CMakeLists.txt
- src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointPlugin.cpp
- src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointPlugin.h
- src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointPlugin.json
- src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointPluginExport.h
- src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.cpp
- src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.h
- src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.cpp
- src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.h
- src/plugins/legacy/iterativeClosestPoint/vtkICPFilter.cxx
- src/plugins/legacy/iterativeClosestPoint/vtkICPFilter.h
This PR adds the ICP toolbox in Meshing workspace. It cleans the vtk reading/writing logs (too much lines before).
:m:
> [music3] add Iterative Closest Point tlbx

- src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
From https://github.com/LoicCadour/medInria-public/pull/96 and https://github.com/Inria-Asclepios/music/pull/231
This Pull Request adds opacity and color parameters to vtkDataMeshInteractor for particular mesh types.
:m:
> [vtk-ish files] opacity and color for some file types

- src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsPlugin.json
Forget to change the name in the json file.
:m:
> [diffeo] right name in json

- src/plugins/CMakeLists.txt
- src/plugins/legacy/medN4BiasCorrection/CMakeLists.txt
- src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection.cpp
- src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection.h
- src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionPlugin.cpp
- src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionPlugin.h
- src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionPlugin.json
- src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionPluginExport.h
- src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionToolBox.cpp
- src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionToolBox.h
- src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection_p.h
This PR adds the N4 Bias Correction toolbox in the Filtering (legacy) workspace.
:m:
> [N4Bias] Filtering tlbx medN4BiasCorrection added

- src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection_p.h
> N4 Bias Correction compilation bug under windows

- src/cmake/medInriaConfig.cmake.in
- src/cmake/module/set_lib_properties_variables.cmake
Correct variable import on windows so that external plugins are able to link
> Correct variables export/import for windows

- src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
Change back something wrongly done in https://github.com/medInria/medInria-public/pull/371 
If the data does not have a name, it takes the file name.
:m:
> [Import] data without name get filename

- src/plugins/legacy/medRegistrationWorkspace/medRegistrationWorkspacePlugin.json
- src/plugins/legacy/medVtkView/medVtkViewPlugin.json
- src/plugins/legacy/polygonRoi/polygonRoiPlugin.json
Last wrong "name" tag in json files.
:m:
> [JSON] Registration workspace and polygonROI

- src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.h
- src/layers/legacy/medCoreLegacy/database/medAbstractDbController.h
- src/layers/legacy/medCoreLegacy/database/medDataManager.cpp
- src/layers/legacy/medCoreLegacy/database/medDataManager.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseController.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseModel.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseModel.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseRemover.cpp
- src/layers/legacy/medCoreLegacy/gui/database/medDatabasePreview.cpp
- src/layers/legacy/medCoreLegacy/tests/medDataManagerTest.cpp
- src/layers/legacy/medCoreLegacy/tests/medDataManagerTest.h
- src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
- src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.h
- src/plugins/legacy/polygonRoi/medRoiManagementToolBox.cpp
Looking at this issue https://github.com/medInria/medInria-public/issues/486 i found 2 errors:
* "Series" is not "Serie":  On some part of the code "seriesId" was used, and at one point (in `medDatabaseController::moveSeries`) "serieId". In order to avoid any other bug, i changed all remaining "serie" to "series".
* In  `medDatabaseRemover::removePatient` i forgot to change that function to add `removeThumbnailIfNeeded` af in `removeSeries` and `removeStudy`.
:m:
> [DB] debug: SeriesId and remove patient thumbnail

- src/layers/legacy/medCoreLegacy/database/medDatabaseModel.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp
Fixes https://github.com/medInria/medInria-public/issues/490
You can remove a patient, study, series, being the last of its kind, or not. The main changes are in `medDatabaseNonPersistentController::remove` and `medDatabaseNonPersistentController::studies`.
:m:
> [DB] solve temporary index removal 

- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImage4DInteractor.cpp
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
- src/plugins/legacy/medSegmentation/medAnnotationInteractor.cpp
first step to correct   " Memory issues when getting rid of images #486 "
m_poConv correction.
> itkvtk converter deletion 

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
For a good part Fix #486 "Memory issues when getting rid of images"
> Correction of a big part for memory issues

- README.md
This PR update the readme:
* Asclepios -> Epione. By the way, Visages changed its name also, isn't it?
* Remove the compilation steps to centralize on the final documentation. At the end, it would be on medInria website i think, but for now i put the new dev guide on Florent's github. It could be changed quickly as soon as a new one appears.
* markdown links.
* the copyright.
edit: guide dev issue: https://github.com/medInria/medInria-public/issues/498
:m:
> [Documentation] update readme

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
- src/plugins/legacy/meshManipulation/meshManipulationToolBox.cpp
- src/plugins/legacy/polygonRoi/polygonRoiToolBox.cpp
- src/plugins/legacy/reformat/medCropToolBox.cpp
- src/plugins/legacy/reformat/medResliceViewer.cpp
- src/plugins/legacy/reformat/resliceToolBox.cpp
- src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
- src/plugins/legacy/voiCutter/voiCutterToolBox.cpp
Avoid crashs using vector images in non-vector plugins.
:m:
> [VectorImages] avoid crashs/errors with vector images in wrong plugins

- src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
- src/layers/legacy/medImageIO/itkDCMTKImageIO.h
- src/plugins/legacy/qtdcmDataSource/qtdcmDataSource.cpp
- src/plugins/legacy/qtdcmDataSource/qtdcmDataSource.h
- superbuild/projects_modules/DCMTK.cmake
Uses updated signals in QtDCM
Corrects bug when dicom files were not ordered on the Z axis
> Qtdcm corrections

- CONTRIBUTING.md
This PR can be updated if needed. This is a suggestion to enhance the CONTRIBUTING file explaining the rules/guidelines to work on medInria.
Do not hesitate to discuss it on this PR if needed.
:m:
> [CONTRIBUTING] suggestion of enhancement

- src/plugins/legacy/vtkDataMesh/readers/vtkDataMesh4DReader.cpp
- src/plugins/legacy/vtkDataMesh/readers/vtkDataMesh4DReader.h
- src/plugins/legacy/vtkDataMesh/readers/vtkDataMeshReader.cpp
- src/plugins/legacy/vtkDataMesh/readers/vtkDataMeshReader.h
- src/plugins/legacy/vtkDataMesh/readers/vtkDataMeshReaderBase.cpp
- src/plugins/legacy/vtkDataMesh/readers/vtkDataMeshReaderBase.h
- src/plugins/legacy/vtkDataMesh/writers/vtkDataMesh4DWriter.cpp
- src/plugins/legacy/vtkDataMesh/writers/vtkDataMesh4DWriter.h
- src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriter.cpp
- src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriter.h
- src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriterBase.cpp
- src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriterBase.h
From comments on this PR https://github.com/medInria/medInria-public/pull/522, clean a bit the code of vtk readers and writers.
:m:
> [reader/writer] clean code according to PR 522

- src/layers/legacy/medImageIO/vtkItkConversion.tpp
- src/layers/legacy/medVtkInria/vtkImageView/vtkImage2DDisplay.cpp
- src/layers/legacy/medVtkInria/vtkImageView/vtkImage2DDisplay.h
- src/layers/legacy/medVtkInria/vtkImageView/vtkImage3DDisplay.cpp
- src/layers/legacy/medVtkInria/vtkImageView/vtkImage3DDisplay.h
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.h
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImage4DInteractor.cpp
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
An equivalent PR for milestone 4.0 is #539
> Viewer optimization v3.1.1

- src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2DCommand.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageViewCornerAnnotation.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageViewCornerAnnotation.h
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h
Equal to https://github.com/medInria/medInria-public/pull/549 on the 3.1.x branch + a previous debug in medDatabaseController::createSeriesTable()
:m:
> [3.1.1] window/level lag + annotatedCube + annotation layer + createSeriesTable return

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
forgot lines in previous PRs because of rebase.
:m:
> [View3D] setInputLayer forgot lines in rebase from master

- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h
Fixes https://github.com/medInria/medInria-public/issues/558
This bug (and some others since the current layer was wrong) has been created https://github.com/medInria/medInria-public/pull/549. 
I may have to do the same on the master.
:m:
> [ViewInteractor] wrong current layer creates bugs

- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h
Same as https://github.com/medInria/medInria-public/pull/559 on master.
:m:
> [ViewInteractor] wrong current layer creates bugs - master

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageViewCornerAnnotation.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageViewCornerAnnotation.h
Same as https://github.com/medInria/medInria-public/pull/568 on master
:m:
> [Annotation] slice numbers and zoom txt -- master

- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Equivalent for medInria 4.0 of #564
> 4D load crash medInria medV4

- src/layers/legacy/medCoreLegacy/data/medAbstractImageData.h
- src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBox.cpp
- src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
- src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
- src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.h
- src/layers/legacy/medCoreLegacy/process/medRunnableProcess.cpp
- src/layers/legacy/medCoreLegacy/views/medAbstractView.cpp
- src/layers/legacy/medCoreLegacy/views/medAbstractView.h
- src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
- src/plugins/legacy/itkFilters/itkFiltersToolBox.h
- src/plugins/legacy/itkFilters/itkMorphologicalFiltersToolBox.cpp
- src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp
- src/plugins/legacy/medVtkView/medVtkView.cpp
- src/plugins/legacy/medVtkView/medVtkView.h
Solves https://github.com/medInria/medInria-public/issues/587 i.e in the Threshold an image toolbox:
* click on the Histogram button: no more crash
* the sliders were missing ranges: they can be used
* click on the Histogram button: it takes so long to open (but that's normal) that i put the toolbox in wait mode
BTW, i saw an other problem with this toolbox. If you Run twice, there are some buttons and display problems, as if something is running in loop somewhere. I'll investigate too. And also i'll do the PR on master at the end.
:m:
> [Threshold] histogram and slider problems

- src/layers/legacy/medCoreLegacy/data/medAbstractImageData.h
- src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBox.cpp
- src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
- src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
- src/layers/legacy/medCoreLegacy/process/medRunnableProcess.cpp
- src/layers/legacy/medCoreLegacy/views/medAbstractView.cpp
- src/layers/legacy/medCoreLegacy/views/medAbstractView.h
- src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
- src/plugins/legacy/itkFilters/itkFiltersToolBox.h
- src/plugins/legacy/itkFilters/itkMorphologicalFiltersToolBox.cpp
- src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp
- src/plugins/legacy/medVtkView/medVtkView.cpp
- src/plugins/legacy/medVtkView/medVtkView.h
Copy of https://github.com/medInria/medInria-public/pull/589 on master
Fixes https://github.com/medInria/medInria-public/issues/587
:m:
> [Threshold] histogram and slider problems -- master

- src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBox.cpp
- src/layers/legacy/medCoreLegacy/medMessageController.cpp
- src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
Fix https://github.com/medInria/medInria-public/issues/584
No more duplication of outputs with Variation Segmentation toolbox.
I will have to create the same PR on master.
:m:
> [Variational] solve the 2 outputs problem

- src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBox.cpp
- src/layers/legacy/medCoreLegacy/medMessageController.cpp
- src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
identical to https://github.com/medInria/medInria-public/pull/597 on master
Solve the 2 outputs problem in the Variational Segmentation toolbox.
:m:
> [Variational] solve the 2 outputs problem -- master

- src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
- src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
- src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
- src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
Same as https://github.com/medInria/medInria-public/pull/599 but on master branch.
Solve the Cropping/Reslice view size bug.
:m:
> [ViewContainer] bug with reslice/crop size, and small enhancements -- master

- src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
- src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
- src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
- src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
- src/plugins/legacy/itkFilters/itkFiltersToolBox.h
Fix https://github.com/medInria/medInria-public/issues/586
And some merge problem in itkFiltersToolbox, add some Qt::UniqueConnection, and enhancements in medDoubleParameters.
:m:
> [ViewContainer] bug with reslice/crop size, and small enhancements

- src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSet.cxx
- src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSet.h
- src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.cxx
- src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.h
- src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.cxx
- src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx
- src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
- src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.h
- Cherry-pick from medInria3.1.X  #605
> [4D mesh - master] Fix attribute intensity problem 

- src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.cpp
- src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h
- src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentItem.cpp
- src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp
- src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
- src/layers/legacy/medImageIO/itkDCMTKImageIO.h
- src/layers/legacy/medUtilities/medUtilities.cpp
- src/plugins/legacy/itkDataImage/itkDataImagePlugin.cpp
- src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
- src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
- src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.h
- Add Dicom image series export, based on work by Pauline Migerditichan.
- Remplace erroneous 'StudyDicomID' and 'SeriesDicomID' tags by correct 'StudyInstanceUID' and 'SeriesInstanceUID' tags.
> [medInria3.1.x] Add DICOM image series export

- src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
- src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.cxx
Fix https://github.com/medInria/medInria-public/issues/614
This is a quick debug to compile https://github.com/medInria/medInria-public/pull/609, but i did not test the 609 PR. 
NB: the master PR of the 609 has not been done, that's why the master compiled.
:m:
> [Dicom] quick debug of dicom PR to compile

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
Equal to https://github.com/medInria/medInria-public/pull/623 on master. Solve the crash with @nbaraka data.
Fix https://github.com/medInria/medInria-public/issues/603
:m:
> [nrrd/nhrd/nrrd] debug crash opening Nordine data -- master

- src/app/medInria/QSingleApplication/qtsingleapplication.cpp
- src/app/medInria/QSingleApplication/qtsingleapplication.h
- src/app/medInria/medSplashScreen.cpp
- src/layers/legacy/medCoreLegacy/CMakeLists.txt
- src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
- src/plugins/legacy/medVtkView/medVtkView.cpp
Same as https://github.com/medInria/medInria-public/pull/618on master.
:m:
> [Q_OS_X11] changes from Qt4->5, code was not used -- master

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
- src/plugins/legacy/medVtkView/medVtkViewNavigator.cpp
> [medVtkInria] solve opacity always at 0 - rm setInput to null - SetOtherLayer enhancement

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
Fix #583 VR not displayed without change LUT
> Fix #583 VR not displayed without change LUT

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
> [medVtkInria] solve opacity always at 0 - rm setInput to null - SetOtherLayer enhancement 4 Master

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
Add tests when getting a pointer from a function that could return a nullptr.
> add some test before dereferencing pointers

- src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
- src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp
Working on https://github.com/medInria/medInria-public/issues/593 i found some duplication of signals. 
:m:
> [FilteringWorkspaceL] remove signals duplication

- src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
- src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp
Same as https://github.com/medInria/medInria-public/pull/631 on master.
:m:
> [FilteringWorkspaceL] remove signals duplication -- master

- src/plugins/legacy/medVtkView/medVtkView.cpp
Same as https://github.com/medInria/medInria-public/pull/635 on master branch.
:m:
> [Views] remove flickering, add back thumbnails -- master

- src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
> Correction of very low windowLevel images (range < 10^-2)

- src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.cxx
- src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx
I copied/paste the @mjuhoor PR from medInria3.1.x branch to master. I did not really test it aside from importing and opening a classic mesh.
:m:
> [Meshes] Add support for medit .mesh file format -- master

- src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
Same as https://github.com/medInria/medInria-public/pull/641 on master.
:m:
> [Menu Links] Layer group 1 appears in link view properties -- master

- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Same as https://github.com/medInria/medInria-public/pull/646 on master.
:m:
> [Ubuntu18.04] compilation ceill fabsl log10l -- master

- src/app/medInria/medDataSourceManager.cpp
- src/app/medInria/medDataSourceManager.h
- src/app/medInria/medFileSystemDataSource.cpp
- src/app/medInria/medFileSystemDataSource.h
- src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp
- src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.cpp
- src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.h
- src/layers/legacy/medCoreLegacy/medAbstractDataSource.h
Same as https://github.com/medInria/medInria-public/pull/658 on master.
:m:
> [Browser] View, Index, dbl-click, Bookmark cleaning -- master

- src/plugins/legacy/polygonRoi/data/polygonRoi.cpp
- src/plugins/legacy/polygonRoi/medTagRoiManager.cpp
- src/plugins/legacy/polygonRoi/medTagRoiManager.h
- src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
- src/plugins/legacy/polygonRoi/polygonEventFilter.h
- Inactive contour: Replace transparency by colored contours with less opacity
- Change cursor: Create custom (red circle) cursor when mouse is near a node
- Remove thickness on contour when selected
> Apply Feedback from APHP

- src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
Fix https://github.com/medInria/medInria-public/issues/557
Remove a warning "elems" in a loop.
:m:
> [itkDCMTKImageIo] remove elems warning

- src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
Same as https://github.com/medInria/medInria-public/pull/662 on master.
:m:
> [itkDCMTKImageIo] remove elems warning -- master

- src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
- src/plugins/legacy/polygonRoi/polygonEventFilter.h
- src/plugins/legacy/polygonRoi/polygonRoiToolBox.cpp
- src/plugins/legacy/polygonRoi/polygonRoiToolBox.h
1. Add ComboBox with specialities 
- For now, only default and prostate
- We could add cardiology and brain for instance
- It is hardcoded actually. 
- In a future PR, I would like to add a json configuration file to allow users adding new speciality dynamically
2. When a speciality is selected, a listWidget appears with a list of predefined label name according to speciality
- Ability to choose the order (drag and drop)
- ability to add label name
- the choice must be validated with the "set predefined label" button
> [PolygonROI] - Menu predefined labels according to speciality

- src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.cpp
- src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h
- src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentItem.cpp
- src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp
- src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
- src/layers/legacy/medImageIO/itkDCMTKImageIO.h
- src/layers/legacy/medUtilities/medUtilities.cpp
- src/plugins/legacy/itkDataImage/itkDataImagePlugin.cpp
- src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
- src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
- src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.h
port of mjuhoor:addDicomExport3.1 branch for medInria4.0
see #609
> [medInria4.0] Add DICOM image series export

- src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
As https://github.com/medInria/medInria-public/pull/615 in order to compile @mjuhoor  PR.
:m:
> [Dicom] quick debug of dicom PR to compile -- master

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
Port for 3.1.1 of the PR of medInria 4.0:
Changes related to "2 Volume VR & LUT #657" (PR of medInria 4.0) to improve volume rendering and solve crash when closing a data layer.
> Vtk not smart4 3.1

- src/plugins/legacy/reformat/medResliceViewer.cpp
- src/plugins/legacy/reformat/medResliceViewer.h
- src/plugins/legacy/reformat/resliceToolBox.cpp
- src/plugins/legacy/reformat/resliceToolBox.h
port of nbaraka:spacingReslicer
equivalent to #672 in parameters retrieving
RESLICER crash with some parameters #669
> [medInria3.1.x]solve #669 in parameters retrieving

- src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
- src/plugins/legacy/LCCLogDemons/LCCLogDemons.cpp
- src/plugins/legacy/LCCLogDemons/LCCLogDemons.h
- src/plugins/legacy/LCCLogDemons/LCCLogDemonsToolBox.cpp
- src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.cpp
- src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp
- src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp
Same as https://github.com/medInria/medInria-public/pull/699 + https://github.com/medInria/medInria-public/pull/700
:m:
> [LCC-LogDemons] avoid crashes (transfo, spacing, size) -- master

- src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Solve the compilation crash introduced by https://github.com/medInria/medInria-public/pull/693
I'm going to create the same on 3.1.1.
:m:
> [Registration] undo-redo current tlbx name -- master

- src/app/medInria/CMakeLists.txt
- src/app/medInria/medLogger.cpp
use utf16 for paths on Windows
> Improve log redirection for windows

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
Solve: 
> 3D mode crash for Image with vector data or tensor when data is 2D: "itkDataImageVectorFloat3 #640
> Solve Glyph 2D into 3D rendering

- src/plugins/legacy/polygonRoi/toolboxes/contoursManagementToolBox.cpp
> [FIX] - Label name disappears when switching anat. & target with SwitchButton

- src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
Fix https://github.com/medInria/medInria-public/issues/711
@juliencastelneau there were several devicePixelRatio problems in the file. If needed, you can add commits to this PR, or create new ones, etc.
:m:
> [PolygonROI] devicePixelRatio on Qt < 5.10

- src/layers/legacy/medVtkInria/CMakeLists.txt
Never used now and dangerous for visages plugins
> [V3.1.x] clean medVtkInria cmake

- src/layers/legacy/medVtkInria/CMakeLists.txt
Never used now and dangerous for visages plugins
> [V4.0] clean medVtkInria cmake

- src/plugins/legacy/polygonRoi/toolboxes/contoursManagementToolBox.cpp
> [FIX] Avoid capability to save contour if there is not inside the view

- src/plugins/legacy/medSegmentation/medAnnotationInteractor.cpp
Fix issue #582
Force medVtkView2D to refresh during a paint segmentation.
> [V3.1.1] Paint - drawing not refresh

- src/plugins/legacy/medSegmentation/medAnnotationInteractor.cpp
Fix issue #582
Force medVtkView2D to refresh during a paint segmentation.
> [V4.0] Paint - drawing not refresh

- src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
Same as https://github.com/medInria/medInria-public/pull/728 on master.
:m:
> [Reslice] Qt AlignCenter created reslice size pb -- master

- src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
Fix https://github.com/medInria/medInria-public/issues/727
Solved by https://github.com/medInria/medInria-public/pull/599/files, problem put back by https://github.com/medInria/medInria-public/commit/7f5e02db9d27164149d7f83b24c5a97f782de1b9#diff-f047aa65ff0f121ac8e2dd9a552b1136
:m:
> [Reslice] Qt AlignCenter created reslice size pb

- RELEASE_NOTES.txt
Last changes in release notes.
:m:
> [ReleaseNotes] last changes in release notes

- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
Cherry pick commit ad153f327b4bf3b2ba1ce2c06cf50ea90e469cb3 to apply fix on master too
> [FIX] - Add PixelDeviceRatio for Retina when MouseEvent is used

- RELEASE_NOTES.txt
Add a line on the 3.1.1 release notes about a dicom exporter.
:m:
> [ReleaseNotes] add dicom exporter

- RELEASE_NOTES.txt
Last 3.1.1 changes in release notes.
:m:
> [ReleaseNotes] last changes in release notes -- master

- src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.cpp
- src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h
- src/layers/legacy/medImageIO/itkDataImageReaderBase.cpp
- src/layers/legacy/medImageIO/itkDataImageReaderBase.h
- src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp
- src/layers/legacy/medImageIO/itkDataImageWriterBase.h
- src/layers/legacy/medUtilities/medUtilities.cpp
- src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
- src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
- src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.h
- Partial cherry pick from https://github.com/Inria-Asclepios/medInria-public/pull/602
- Add DICOM tags and corresponding medMetaDataKeys
- Some refactoring
> [DICOM and medMetaDataKeys] Cherry pick 3.1.1 to master

- CMakeLists.txt
- src/app/medInria/medSearchToolboxDialog.cpp
- src/app/medInria/medSearchToolboxDialog.h
- src/layers/legacy/medCoreLegacy/data/medDataReaderWriter.cpp
- src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
- src/layers/legacy/medImageIO/itkDCMTKImageIO.h
- src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSet.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
- src/plugins/legacy/medVtkView/medVtkView.cpp
Remove some warnings i found, mostly thanks to my new version of IDE: 
* override
* unused parameters
* license
* unused code
:m:
> [Warnings] override and unused warnings

- src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h
- src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp
- src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
To complete https://github.com/medInria/medInria-public/pull/743
Add includes, and PatientOrientation, PatientPosition and ImageType metadata.
:m:
> [medMetaDataKeys] include and metadata added

- src/layers/legacy/medCoreLegacy/medViewEventFilter.cpp
- src/layers/legacy/medCoreLegacy/medViewEventFilter.h
- Add mouse wheel events to the medViewEventFilter
> [medViewEventFilter] Implementation of mouse wheel events.

- packaging/Packaging.cmake
- packaging/apple/mac_packager.sh.in
- packaging/linux/DEB.cmake
- packaging/unix/Launchers.cmake
- src/app/medInria/areas/homepage/medHomepageArea.cpp
- src/app/medInria/main.cpp
- src/app/medInria/medMainWindow.cpp
- src/app/medInria/medPluginWidget.cpp
- src/cmake/module/set_exe_install_rules.cmake
- src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
- src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.h
- src/layers/legacy/medCoreLegacy/database/medDataIndex.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.h
- src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.cpp
- src/layers/legacy/medCoreLegacy/medPluginManager.h
- src/layers/legacy/medCoreLegacy/views/interactors/medAbstractInteractor.h
- src/layers/legacy/medCoreLegacy/views/medAbstractImageView.h
- src/layers/legacy/medCoreLegacy/views/medAbstractView.h
- src/plugins/legacy/medSegmentation/medSegmentationPlugin.h
- src/plugins/legacy/medVtkFibersData/interactors/medVtkFibersDataInteractor.cpp
- src/plugins/legacy/qtdcmDataSource/qtdcmDataSourcePlugin.cpp
We talked about the customization of medInria 4 for external projects (like music), with for instance a custom directory/json with dedicated external projects logo, names, theme, description, license, release notes, etc. Cf https://github.com/Inria-Asclepios/medInria-public/pull/606 on our music fork with the needs in term of customization.
This PR simplifies the customization with simple comment changes and shared variables. 
:m:
> [Custom] prepare customization of medInria for ext projects

- src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.cpp
> mem leak on medClutEditor

- src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
> [vtkDataMeshInteractor 3.1.1] Fix mesh LUT messing with image LUT

- superbuild/patches/VTK.patch
Fixes https://github.com/medInria/medInria-public/issues/772
This update the VTK patch with 2 includes to compile on some mac.
:m:
> [VTK] update patch with QPainterPath

- src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medDatabaseSettingsWidget.cpp
- Switching to an existing database sometimes poses problem. This fixes the problem.
I am not sure if this may introduce problems elsewhere. Does someone know ?
> [Database] Allow switch to existing database

- src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medDatabaseSettingsWidget.cpp
> [Database 3.1.1] Allow switch to existing database

- RELEASE_NOTES.txt
This PR adds the 3.2 changes in the release notes file. It could be added with more changes, and i think should be merged just before the release, to be sure to have all the changes.
:m:
> [ReleaseNotes] add 3.2 additions/changes/debug

- superbuild/CMakeLists.txt
Avoid a duplication of external projects lines with or without dtkImaging.
:m:
> [ExternalProjects] avoid duplication with dtkImaging

- src/layers/legacy/medUtilities/CMakeLists.txt
- src/layers/legacy/medUtilities/medUtilities.cpp
- src/layers/legacy/medUtilities/medUtilities.h
- Copy of https://github.com/Inria-Asclepios/medInria-public/pull/633
> 
Add function to generate DICOM UIDs
Add function to add a StudyId and StudyInstanceUID to a medAbstractData
Use gdcm to generate UIDs
> [medUtilities] Study UID generation with gdcm

- superbuild/external_projects_tools/EP_CheckEnvironment.cmake
Reduces file length for full display on one scr
homogenization with anima project
https://github.com/Inria-Visages/Anima-Public/pull/72
> Improve find_program bash

- src/plugins/legacy/meshManipulation/meshManipulationToolBox.cpp
- src/plugins/legacy/meshManipulation/meshManipulationToolBox.h
- Mesh manipulation applies transformations to EP maps
> [MeshManipulation] Transform properly applied to EP maps

- src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp
- src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.h
> medStatusBar become threadsafe to prevent crash V4

- src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp
- src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.h
> medStatusBar become threadsafe to prevent crash V3.1.x

- src/app/medInria/medLogger.cpp
- src/app/medInria/medLogger.h
(cherry picked from commit 32af87d18e1f4ef99558bb72f455a9caecac3744)
> medLoggerRedirectWithBoost

- superbuild/projects_modules/DCMTK.cmake
- superbuild/projects_modules/ITK.cmake
- superbuild/projects_modules/LogDemons.cmake
- superbuild/projects_modules/QtDCM.cmake
- superbuild/projects_modules/RPI.cmake
- superbuild/projects_modules/TTK.cmake
- superbuild/projects_modules/VTK.cmake
- superbuild/projects_modules/dtk.cmake
- superbuild/projects_modules/dtkImaging.cmake
Originally on https://github.com/medInria/medInria-public/pull/781
Put ALWAYS_BUILD at 0 to avoid complete recompilation all the time.
:m:
> [CMake] ALWAYS_BUILD at 0 except medInria

- src/layers/legacy/medUtilities/medUtilities.cpp
This PR adds 2 includes in medUtilities, to compile on some computers as Ubuntu 18 Jenkins for MUSICardio.
:m:
> [medUtilities] add includes for Ubuntu18

- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
fix https://github.com/medInria/medInria-public/issues/790
> [PaintToolBox]: fix crash

- src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
- src/layers/legacy/medImageIO/itkDataImageReaderBase.cpp
- src/layers/legacy/medImageIO/itkGISImageIO.cpp
- src/layers/legacy/medImageIO/medInrimageImageIO.cpp
- src/layers/legacy/medImageIO/medInrimageImageIO.h
- src/layers/legacy/medUtilities/CMakeLists.txt
- src/plugins/legacy/LCCLogDemons/CMakeLists.txt
- src/plugins/legacy/diffeomorphicDemons/CMakeLists.txt
- src/plugins/legacy/itkDataImage/CMakeLists.txt
- src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
- src/plugins/legacy/itkDataImage/readers/itkGDCMDataImageReader.cpp
- src/plugins/legacy/itkDataSHImage/readers/itkDataSHImageReader.cpp
- src/plugins/legacy/itkDataTensorImage/readers/itkDataTensorImageReaderBase.cpp
- src/plugins/legacy/itkFilters/CMakeLists.txt
- src/plugins/legacy/itkProcessRegistrationOptimus/CMakeLists.txt
- src/plugins/legacy/medAlgorithmPaint/CMakeLists.txt
- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
- src/plugins/legacy/medSegmentation/CMakeLists.txt
- src/plugins/process/itkDWIBrainMaskCalculatorProcess/CMakeLists.txt
- src/plugins/process/single_filter/CMakeLists.txt
- superbuild/projects_modules/ITK.cmake
- superbuild/projects_modules/LogDemons.cmake
- superbuild/projects_modules/RPI.cmake
- superbuild/projects_modules/TTK.cmake
> 1st step to move on ITK5.1.1

- src/plugins/legacy/medRemeshing/medRefineMeshProcess.cpp
fix https://github.com/medInria/medInria-public/issues/796
> [Remeshing]: check if output is empty

- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
fix https://github.com/medInria/medInria-public/issues/810
> [PaintToolBox]: fix crash due to current view being badly updated afrer creating a mask

- src/layers/legacy/medUtilities/medUtilitiesITK.cpp
- src/layers/legacy/medUtilities/medUtilitiesITK.h
- src/layers/legacy/medUtilities/statsROI.cpp
- src/layers/legacy/medUtilities/statsROI.h
statsROI::runMeanVariance function was badly named and computes mean and standard deviation.
:m:
> [StatROI] variance was a std deviation computation

- superbuild/projects_modules/DCMTK.cmake
- superbuild/projects_modules/ITK.cmake
- superbuild/projects_modules/VTK.cmake
The BUILD_ALWAYS at 0 created patch error at the packaging step.
:m:
> [Package] package fails because of patchs

- packaging/windows/WindowsPackaging.cmake
This is during packaging phase.
> Incorporated external plugins to folders of built-in plugins

- CONTRIBUTING.md
Attempt to make branching and development rules for different branches as explicit as possible
> Add dev rules on branches to CONTRIBUTING.md

- superbuild/projects_modules/LogDemons.cmake
- superbuild/projects_modules/RPI.cmake
Change **LCC** and **RPI** repositories to use _Inria-Asclepios_
> Change some ep repo

- src/cmake/module/set_plugin_install_rules.cmake
> replace code forgotten during cherry-pick

- src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
- Use QDir::separator for paths
- Remove duplicated SeriesInstanceUID assignment
> [medAbstractDatabaseImporter] QDir::separator 

- CONTRIBUTING.md
From a comment originally on https://github.com/medInria/medInria-public/pull/761
Explain how to handle cherry-picking manually.
:m:
> [Contributing] contributers use PR not direct commits

- src/plugins/legacy/medCreateMeshFromMask/medCreateMeshFromMask.cpp
- src/plugins/legacy/medCreateMeshFromMask/medCreateMeshFromMask.h
minor memleak on medCreateMeshFromMask
> minor memleak on medCreateMeshFromMask

- src/plugins/legacy/voiCutter/voiCutterToolBox.cpp
missing delete on two QList. (done some tests : amazing toolbox) and on destructor.
> minor memory leak in voiCutterToolBox

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
missing delete on qtSignalHandler.
> memory leak on vtkImageView2D 

- src/layers/legacy/medCoreLegacy/CMakeLists.txt
- src/layers/legacy/medCoreLegacy/computerInfo/computerInfo.h
- src/layers/legacy/medCoreLegacy/computerInfo/cpu.cpp
- src/layers/legacy/medCoreLegacy/computerInfo/networkAndNaming.cpp
- src/layers/legacy/medCoreLegacy/computerInfo/ram.cpp
Into a namespace **medComputerInfo** add these functions to the API
```C++
/******************************************************
*** CPU
******************************************************/
int MEDCORELEGACY_EXPORT getNbOfCores();
int MEDCORELEGACY_EXPORT getloadavg (double *loadavg);
/******************************************************
*** MEMORY
******************************************************/
MEDCORELEGACY_EXPORT void ramInfo(long long &totalRam, long long &usageRam);
/******************************************************
*** MACHINE NAME  AND  NETWORK
******************************************************/
MEDCORELEGACY_EXPORT bool           isMyComputer(char const* pi_pchBuffIn);
MEDCORELEGACY_EXPORT bool           getIPFromName(char const* pi_pchHostName, char*** …
```
> put computerInfo code

- src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.cpp
- add the icp transformation matrix inside a field data
> [IterativeClosestPoint]: transformation matrix is saved inside dataset to be used in mesh manipulation toolbox

- src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.h
- Fixes #820
- SQL request is restricted to the study if possible
> [medDatabase] Fix suffix added to series

- src/plugins/legacy/itkDataImage/writers/itkMetaDataImageWriter.cpp
- On Save =>  images are saved in db in .mha
- On Export:
> [MHA] itk save default format : mha

- src/app/medInria/main.cpp
- src/layers/medPython/core/medPythonCore.cpp
- src/layers/medPython/core/medPythonCoreFunction.h
- src/layers/medPython/core/medPythonCoreUtils.cpp
- src/layers/medPython/core/medPythonCoreUtils.h
- src/layers/medPython/medPythonInit.cpp
- src/layers/medPython/medPythonInit.h
- src/layers/medPython/objects/medPythonAbstractObject.cpp
- src/layers/medPython/objects/medPythonAbstractObject.h
- src/layers/medPython/objects/medPythonContainerAccessor.cpp
- src/layers/medPython/objects/medPythonFunctionCall.cpp
- src/layers/medPython/objects/medPythonObject.h
- src/layers/medPython/objects/medPythonStandardObjects.cpp
Introduces lazy loading of Python (which was asked by @Florent2305 ). The Python library is now loaded and initialized when the wrapping API is first used.
(this change removes the need for the **--no-python** option)
> [medPython] Lazy loading

- src/layers/medCore/dataSource/medDataModel.cpp
- src/layers/medCore/dataSource/medDataModel.h
- src/layers/medCore/dataSource/medDataModelElement.cpp
- src/layers/medCore/dataSource/medDataModelElement.h
- src/layers/medCore/dataSource/medDataModelItem.cpp
- src/layers/medCore/dataSource/medDataModelItem.h
Consistent medDataModelElement
Code cleaning
> Consistent medDataModelElement

- src/layers/legacy/medCoreLegacy/gui/medTableWidgetChooser.h
- src/plugins/legacy/polygonRoi/medTagRoiManager.cpp
- src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
- src/plugins/legacy/polygonRoi/toolboxes/contoursManagementToolBox.cpp
- src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
Based on this PolygonROI PR merged on medInria3.2.x branch: https://github.com/medInria/medInria-public/pull/817
This PR solves some crashes and problem due to split and clear methods mainly.
:m:
> [PolygonROI] solve graphical/ergonomy pb and crashes - medInria4

- src/plugins/legacy/reformat/resliceToolBox.cpp
A 1-line PR which:
* fix #920 
* fix #916
The removal of the data in the view did not reset the currentView variable.
PS: i'm going to create the same PR on master aswell
:m:
> [Reslice] solve crashs after removing a data in view

- src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImage4DInteractor.cpp
fix https://github.com/medInria/medInria-public/issues/850
> [medVtkViewItkDataImage4DInteractor]: fix wrong frameRateComputation

- src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
- src/plugins/legacy/medVtkFibersData/manager/vtkFibersManager.cxx
- src/plugins/legacy/vtkDataMesh/datas/vtkDataMesh4D.cpp
- src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
- Duplicate of https://github.com/Inria-Asclepios/medInria-public/pull/714
> [vtkImageView3D] Improvements

- src/app/medInria/resources/icons/time_backward_step_black.svg
- src/app/medInria/resources/icons/time_backward_step_white.svg
- src/app/medInria/resources/icons/time_forward_step_black.svg
- src/app/medInria/resources/icons/time_forward_step_white.svg
On https://github.com/medInria/medInria-public/pull/907 i forgot to `git add` the new time icons.
There are svg files, Github shows their code but no need to review the svg content.
:m:
> [Icons] forgot to 4 the new time ones

- src/CMakeLists.txt
This PR adds tests on the two cmake policies that were added through the medPython PRs, to avoid cmake version issues.
> Put conditions on cmake policies

- LICENSES_EXT.txt
- src/app/medInria/areas/homepage/medHomepageArea.cpp
- src/app/medInria/areas/homepage/medHomepageArea.h
- src/app/medInria/resources/medInria.qrc
Fix https://github.com/medInria/medInria-public/issues/868
Most licenses ask to be listed in the application. This Pull Request adds an External Licenses action in the application menu.
:m:
> [License] external libs list with licenses and sources links

- src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusPlugin.cpp
Fix https://github.com/medInria/medInria-public/issues/956
Remove a dead URL in Optimus description.
:m:
> [Optimus] remove dead link

- src/plugins/legacy/reformat/resliceToolBox.cpp
Same as https://github.com/medInria/medInria-public/pull/940 on medInria3.2
Fix a crash in reslice switching the spacing/dimension parameters.
:m:
> [Reslice] fix crash with spacing/dim parameters - 3.2

- src/app/medInria/areas/homepage/medHomepageArea.cpp
- src/plugins/legacy/medAPHPDataSource/medAPHP.cpp
- src/plugins/legacy/medAPHPDataSource/sphereDicomWeb/medAbstractAnnotation.h
- src/plugins/legacy/medAPHPDataSource/sphereDicomWeb/medAnnotation.cpp
- src/plugins/legacy/medAPHPDataSource/sphereDicomWeb/medAnnotation.h
Solves two little problems, a graphical problem with the homepage buttons, and a typo in a method name.
:m:
> [DataSources] button homepage and typo

- src/layers/medCore/dataSource/medSourcesLoader.cpp
- src/layers/medCore/dataSource/medSourcesLoader.h
- src/layers/medWidgets/dataSource/widgets/medSourcesSettings.cpp
- src/layers/medWidgets/dataSource/widgets/medSourcesSettings.h
- src/layers/medWidgets/dataSource/widgets/medSourcesSettingsHandlerWidget.cpp
- src/layers/medWidgets/dataSource/widgets/medSourcesSettingsHandlerWidget.h
- src/layers/medWidgets/parameter/medStringParameterPresenter.cpp
- src/layers/medWidgets/parameter/medStringParameterPresenter.h
- create sub widget medSourcesSettingsHandlerWidget 
- change behavior for medSourcesLoader about path of directory that contains sources descriptions.
> Improve architecture medSourcesSettings

- src/layers/medCore/dataSource/medDataModel.cpp
- src/layers/medCore/dataSource/medDataModelItem.cpp
- src/layers/medCore/dataSource/medDataModelItem.h
- src/layers/medCore/dataSource/medSourceItemModel.cpp
- src/layers/medCore/dataSource/medSourceItemModel.h
- src/layers/medWidgets/dataSource/medSourceModelPresenter.cpp
This PR provides source refreshing without lost already loaded data.
The branch refresh source was tested and validated by @juliencastelneau  and @Florent2305.
> Refresh source

- src/app/medInria/areas/browser/medBrowserArea.cpp
- src/layers/legacy/medCoreLegacy/gui/medToolBoxContainer.cpp
fix https://github.com/medInria/medInria-public/issues/1016
> Show toolboxes even after switching workspace

- RELEASE_NOTES.txt
Add new points on release note page for 3.3.
:m:
> [Release Notes] prepare notes for 3.3

- src/layers/legacy/medCoreLegacy/gui/toolboxes/medSelectorToolBox.cpp
Following a comment by @fcollot in https://github.com/medInria/medInria-public/pull/967
Simplify code.
:m:
> [Selector] nothing done if same tlbx switched

- src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
Small error in this warning.
:m:
> [Comment] small error creating warning

- src/plugins/legacy/polygonRoi/polygonLabel.cpp
- src/plugins/legacy/polygonRoi/toolboxes/defaultLabelToolBox.cpp
- src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
- src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.h
This PR:
* enhance the GUI for a better use by users
* enhance the help pop up
* remove a small compilation warning
* remove a warning/error message shown at opening of the toolbox
:m:
> [PolygonRoi] enhance GUI/help + warnings at compil/opening

- packaging/apple/mac_packager.sh.in
- src/cmake/module/set_lib_install_rules.cmake
- src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
The medInria3.4.x branch is slightly behind on medInria3.3.x
> rebase from medInria3.3.x

- src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Avoid trying to connect with an empty toolbox in some cases.
:m:
> [Registration] selector toolbox empty connect

- src/app/medInria/medMainWindow.cpp
- src/layers/legacy/medImageIO/itkDataImageReaderBase.cpp
- src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp
- src/plugins/legacy/itkDataImage/readers/itkGDCMDataImageReader.cpp
- src/plugins/legacy/itkDataSHImage/readers/itkDataSHImageReader.cpp
- src/plugins/legacy/itkDataSHImage/writers/itkDataSHImageWriterBase.cpp
- src/plugins/legacy/itkDataTensorImage/readers/itkDataTensorImageReaderBase.cpp
- src/plugins/legacy/itkDataTensorImage/writers/itkDataTensorImageWriterBase.cpp
- src/plugins/legacy/medVtkFibersData/readers/medVtkFibersDataReader.cpp
- src/plugins/legacy/medVtkFibersData/writers/medVtkFibersDataWriter.cpp
- src/plugins/legacy/vtkDataMesh/readers/vtkDataMesh4DReader.cpp
- src/plugins/legacy/vtkDataMesh/writers/vtkDataMesh4DWriter.cpp
Same as https://github.com/medInria/medInria-public/pull/1032 on master branch.
:m:
> [Path] switch to utf8 to accept accented paths

- src/app/medInria/medSearchToolboxDialog.cpp
The minimum size of the "Search Toolbox" tool has been reduced.
:m:
> [SearchTlbx] smaller minimum size of window

- src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
Fix https://github.com/medInria/medInria-public/issues/726
Create the mask data in Paint when the user clicks on "Paint/Erase", not at the first click on the image. The creation of the mask is too slow, and the drawing not smooth at the beginning.
Also, switching from Magic Wand to Paint/Erase was not hiding the removeSeed button.
:m:
> [Paint] create mask before trying to paint + hide a button

- src/layers/legacy/medCoreLegacy/CMakeLists.txt
- src/layers/legacy/medCoreLegacy/database/medDatabaseExporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.h
- src/layers/legacy/medCoreLegacy/readers/medAbstractDataReader.cpp
- src/layers/legacy/medCoreLegacy/readers/medAbstractDataReader.h
- src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
- src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
- src/plugins/legacy/itkINRDataImageReader/CMakeLists.txt
- src/plugins/legacy/itkINRDataImageWriter/CMakeLists.txt
- src/plugins/legacy/medCompositeDataSets/CMakeLists.txt
- src/plugins/legacy/meshMapping/meshMappingToolBox.h
- src/plugins/legacy/undoRedoRegistration/CMakeLists.txt
- src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriterBase.h
Same as https://github.com/medInria/medInria-public/pull/1079
I did some `git diff` between MUSICardio on master branch (3.4) and medInria3.4 for forgot changes. This aims to avoid differences between both code and to avoid having merge problems with synchronisation.
:m:
> [Git diff] solve differences between musicardio to medInria4

- src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Same as https://github.com/medInria/medInria-public/pull/1086 but on master branch.
Avoid trying to connect with an empty toolbox in some cases.
:m:
> [Registration] selector toolbox empty connect --master

- RELEASE_NOTES.txt
Add to master branch the release notes from 3.3
:m:
> [4.0] release notes updated with changes on previous version

- src/plugins/legacy/itkDataImage/itkDataImagePlugin.cpp
- src/plugins/legacy/itkDataImage/writers/dicomRtImageWriter.cpp
- src/plugins/legacy/itkDataImage/writers/dicomRtImageWriter.h
Add a writer for DICOM RT format.
Originally from https://github.com/Inria-Asclepios/medInria-public/pull/600 and https://github.com/Inria-Asclepios/medInria-public/pull/602
Linked with https://github.com/Inria-Asclepios/medInria-public/pull/755
:m:
> [DicomRT] add writer for DICOM RT

- CMakeLists.txt
- src/CMakeLists.txt
- src/app/medPluginGenerator/template/cmake
- src/app/medPluginGenerator/template/filtering/cmake
- src/app/medPluginGenerator/template/registration/cmake
- src/plugins/legacy/itkINRDataImageReader/CMakeLists.txt
- src/plugins/legacy/itkINRDataImageWriter/CMakeLists.txt
- src/plugins/legacy/medCompositeDataSets/CMakeLists.txt
- src/plugins/legacy/undoRedoRegistration/CMakeLists.txt
Same as https://github.com/medInria/medInria-public/pull/1095
Switch cmake minimum to 3.19.
:m:
> [CMake] minimum version at 3.19 --master

- src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
- src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h
- src/layers/medCore/source/medDataHub.cpp
- src/layers/medCore/source/medDataHub.h
- src/layers/medCore/source/virtualRepresentation/medVirtualRepresentation.cpp
Solve a compilation error on Ubuntu 20.04 (in getModelIndex lvalue bug), and fix git diff problems with french accents in comments.
:m:
> [medDataSources] compilation error on Ubuntu + accent err

- src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medDatabaseSettingsWidget.cpp
Enhance/debug the widget in Database settings. There was a graphic bug with `databaseLocation` which was "crunched" vertically.
:m:
> [Settings] solve graphical bug of database widget

- src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
- src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.cpp
Adapt the changed thumbnail code to the new instance system.
:m:
> [Instances] adapt new singleton system to new code

- RELEASE_NOTES.txt
Add new enhancements to the list.
:m:
> [3.4] update release notes with current enhancement

- src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
Remove these deletions which are on static QLists. It created a crash in MUSICardio side that's why i looked at this.
:m:
> [DCMTKreader] roll back on a change on static Qlist

- src/app/medInria/areas/homepage/medHomepageArea.cpp
- src/app/medInria/areas/homepage/medHomepageArea.h
- src/app/medInria/medMainWindow.cpp
- src/app/medInria/medMainWindow.h
Add notif item to main menu
Reconnect notification panel
Move menu mechanism from medHomepageArea to medMainWindow
> Work on menu and notifications

- src/layers/legacy/medCoreLegacy/parameters/medAbstractParameterL.cpp
- src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
- src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.h
- src/layers/legacy/medCoreLegacy/parameters/medParameterPoolL.cpp
- src/layers/legacy/medCoreLegacy/parameters/medTimeLineParameterL.cpp
- src/layers/legacy/medCoreLegacy/parameters/medTimeLineParameterL.h
- src/layers/legacy/medCoreLegacy/views/navigators/medAbstractImageViewNavigator.cpp
- src/layers/legacy/medCoreLegacy/views/navigators/medAbstractNavigator.cpp
- src/plugins/legacy/itkDataImage/navigators/medVtkViewItkDataImageNavigator.cpp
This PR fixes a crash:
* Open a 4D data in a view, then a 3D mask/data
* Close the application -> crash
Parameter label was not well removed.
:m:
> [Close] 4D+3D data in view crash at app closing

- src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
Fix issue: https://github.com/medInria/medInria-public/issues/1190
> Assume 0 for missing origin

- src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
From PR https://github.com/Inria-Asclepios/medInria-public/pull/772 and https://github.com/Inria-Asclepios/medInria-public/pull/777
Allow to get back output from polygonroi toolbox.
:m:
> [polygonRoi] processOutput returned nullptr

- src/layers/legacy/medCoreLegacy/gui/toolboxes/medAbstractSelectableToolBox.h
- src/plugins/legacy/polygonRoi/polygonLabel.cpp
- src/plugins/legacy/polygonRoi/polygonLabel.h
- src/plugins/legacy/polygonRoi/toolboxes/defaultLabelToolBox.cpp
- src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
- src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.h
- src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.cpp
- src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.h
From https://github.com/Inria-Asclepios/medInria-public/pull/766
>  * Add setObjectNames
>  * Add virtual method processOutputs (not pure) to medAbstractSelectableToolBox and polygonRoiToolbox
>  * Add custom metadatakey to be able to retrieve label name at the end of a pipeline step
> [Polygon roi] pipeline adaptation

- src/app/medInria/main.cpp
- src/layers/legacy/medCoreLegacy/database/medAbstractDbController.h
- src/layers/legacy/medCoreLegacy/database/medDataManager.cpp
- src/layers/legacy/medCoreLegacy/database/medDataManager.h
- src/layers/legacy/medCoreLegacy/database/medDataPacsController.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseExporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseExporter.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.h
- src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.h
- src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
- src/layers/legacy/medCoreLegacy/database/medDatabaseRemover.cpp
- src/layers/legacy/medCoreLegacy/database/medLocalDbController.cpp
- src/layers/legacy/medCoreLegacy/database/medLocalDbController.h
- superbuild/CMakeLists.txt
- superbuild/patches/VTK.patch
- superbuild/projects_modules/VTK.cmake
From PR:
* https://github.com/Inria-Asclepios/medInria-public/pull/762
* https://github.com/Inria-Asclepios/medInria-public/pull/763
* https://github.com/Inria-Asclepios/medInria-public/pull/768
* https://github.com/Inria-Asclepios/medInria-public/pull/769
* https://github.com/Inria-Asclepios/medInria-public/pull/780
* https://github.com/Inria-Asclepios/medInria-public/pull/784
These are PR from MUSICardio to debug python in medInria and some other stuff needed for the next medInria release.
:m:
> [Python] commits to debug mostly python in medInria

- superbuild/projects_modules/VTK.cmake
Fix compilation issues of VTK due to symbole export Rules change
> Fix compilation issues of VTK 

- src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
Original PR https://github.com/Inria-Asclepios/medInria-public/pull/812
> [PolygonRoi] clear deactivating the tlbx

- superbuild/patches/ITK_Win.patch
- superbuild/projects_modules/ITK.cmake
>  Add patch for ITK to compile on visual studio 2019

- src/layers/medCore/legacy/parameters/medAbstractParameterL.cpp
- src/layers/medCore/legacy/parameters/medDoubleParameterL.cpp
- src/layers/medCore/legacy/parameters/medDoubleParameterL.h
- src/layers/medCore/legacy/parameters/medParameterPoolL.cpp
- src/layers/medCore/legacy/parameters/medTimeLineParameterL.cpp
- src/layers/medCore/legacy/parameters/medTimeLineParameterL.h
- src/layers/medCore/legacy/views/navigators/medAbstractImageViewNavigator.cpp
- src/layers/medCore/legacy/views/navigators/medAbstractNavigator.cpp
- src/plugins/legacy/itkDataImage/navigators/medVtkViewItkDataImageNavigator.cpp
This PR fixes a crash:
* Open a 4D data in a view, then a 3D mask/data
* Close the application -> crash
Parameter label was not well removed.
:m:
> [Close] 4D+3D data in view crash at app closing --dev

- src/layers/medCore/legacy/gui/settingsWidgets/medDatabaseSettingsWidget.cpp
Same as https://github.com/medInria/medInria-public/pull/1149 on master branch.
> Enhance/debug the widget in Database settings. There was a graphic bug with `databaseLocation` which was "crunched" vertically.
:m:
> [Settings] solve graphical bug of database widget --master

- src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
On 4.0 branch, cleans the way medVtkImageInfo is called in vtkImageView2D file.
:m:
> [medVtkImageInfo] 4.0 remove unnecessary calls in vtkImageView2D

- src/layers/medCore/source/settings/medSourcesLoader.cpp
Debug compilation on dev branch on Ubuntu.
:m:
> [medSourcesLoader] on Ubuntu const error

- RELEASE_NOTES.txt
Add release notes for medInria 5.
:m:
> [ReleaseNotes] medInria 5

- packaging/apple/mac_packager.sh.in
- packaging/linux/LinuxPackaging.cmake
- packaging/windows/WindowsPackaging.cmake
- src/CMakeLists.txt
- src/app/medInria/CMakeLists.txt
- src/app/medInria/main.cpp
- superbuild/CMakeLists.txt
- superbuild/projects_modules/medInria.cmake
- superbuild/projects_modules/pyncpp.cmake
A port of the Python integration from medInria 4
> Add Python
