medInria/medInria-public

src-plugins/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp, src-plugins/itkDataImage/writers/itkGiplDataImageWriter.cpp, src-plugins/itkDataImage/writers/itkMetaDataImageWriter.cpp, src-plugins/itkDataImage/writers/itkNiftiDataImageWriter.cpp
This fixes 2 problems : the viewer can actually display uchar vector 3 as RGB but there was a typo in the identifier, so they weren't properly recognised. Secondly, the Meta Image, Gipl and Nifti writers were claiming to handle RGB/RGBA when they actually degrade them to uchar vector 3, so I disabled support for writing RGB/RGBA files with these. Which means now RGB/RGA images are saved as Nrrd, which is the only writer we have that actually saves them properly as RGB/RGBA.
This triggers another, more general question of how to handle vector images... a vector uchar 3 is now currently being interpreted as a RGB image, but it could just as well be a vector field image with uchar vector coordinates. What do we think is the best way to deal with ambiguities such as these ? There should …
=> Remove RGB(A) image support in writer that don't actually support it

src/medCore/data/medAbstractData.cpp, src/medCore/database/medAbstractDatabaseImporter.cpp, src/medCore/gui/database/medDatabasePreview.cpp, src/medCore/gui/database/medDatabaseView.cpp
This PR should correct a crash that happened when you were hovering the thumbnail area after creating a new study
=> Crash when empty study

src/medRegistration/itkProcessRegistration.cpp
Reenabling registration for unsigned short images (like I1.nhdr) that was not possible in medInria2.2.2
=> Fix registration for unsigned short images

app/medInria/main.cpp
Otherwise it can be very annoying for the edition of some widgets such as QDoubleSpinbox on some systems:
The SpinBox allow to edit only with coma as floating separator but allow to only display dot.
After this patch, dot is always used.
=> Set default Local of Qt as the C one

src-plugins/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
The invert intensity image filter is broken and make always images with really high values (1.798^308)
If you change the WL of the resulting image, it try to apply a window or a level with NaN and it crashes. Here is a patch to fix the crashes caused by the NaN.
I'll fix the invert intensity image filter soon.
=> Add tests on NaN values to avoid crash during window-leveling

src-plugins/itkFilters/itkFiltersInvertProcess.cpp
Invert image filter doesn't work with double and float images
=> Deactivate invert image filter for double and float images.

app/medPluginGenerator/medPluginGenerator.h, src/medCore/data/medAbstractData.cpp, src/medCore/data/medAbstractData.h
Converters were allowed by DTK abstract data to define conversions between data types. For some old data types that we still use for demos, I had to bring them back in medAbstractData. It can be something useful for future data types people will handle.
This also solves a bug on mac where the plugin generator was generating a registration plugin when we were asking for a filtering plugin
=> Bringing back data converters

app/medInria/medApplication.cpp, src-plugins/itkDataImage/datas/itkDataImage.h, src-plugins/itkDataImage/datas/itkDataPrivateTypes.h, src/medCore/data/medAbstractTypedImageData.h
This is a cleanup of itkDataImage. Several things where done:
- Put the private types in their own header file.
- Suppressed number of includes that were no longer used.
- Simplify the mecanism that uses two different private types for scalar and vectorial type. No longer use a ugly specialization. I believe the stuff is now simpler.
Future work: Split further itkDataPrivateTypes.h ???
=> Itk data improvements

src/medVtkInria/vtkImageView/vtkImageView.cxx, src/medVtkInria/vtkImageView/vtkImageView.h
This is the most elegant way IMO to always have a good display of any value (either very small or very big).
It also fix the Nan bug on windows (CRASH) (DrawNanValue is coming with Vtk 6 to correctly display Nan values on the scalar bar.
=> Change format of scalar bar text to scientific

src/medVtkInria/vtkWidgetsAddOn/vtkInteractorStyleTrackballCamera2.cxx
Previous behaviour :
Open mesh in VR mode
Hold CTRL and leftmouse, and move mouse horizontally, to rotate camera around the Z-axis.
Hold leftmouse and move mouse horizontally - doesn't correctly rotate around the Y-axis anymore.
New behaviour:
As above, except rotation around the Y-axis is no longer broken by rotating around the Z-axis.
The problem came from the fact that z-rotation is handled by vtk directly, while x and y rotation is handeld by our own code, that relies upon certain variables being updated. vtk obviously doesn't update those variables, as it doesn't know about them, so we don't correctly handle the change in camera y-axis after a z-rotation.
=> Fix for broken camera

src/medImageIO/itkDCMTKImageIO.cpp
fix for wrong duration of cardiac sequences by setting the right resolution time. some sequences stil have problems, maybe due to parallel imaging.
=> Try to read temporal resolution from DICOM tag "Repetition Time"

app/medInria/resources/CMakeLists.txt, cmake/module/set_lib_install_rules.cmake, cmake/module/set_plugin_install_rules.cmake, src-plugins/medItkAddImageProcess/medItkAddImageProcess.h, src-plugins/medItkAddImageProcess/medItkAddImageProcessPlugin.h, src-plugins/medItkDivideImageProcess/medItkDivideImageProcess.h, src-plugins/medItkDivideImageProcess/medItkDivideImageProcessPlugin.h, src-plugins/medItkMultiplyImageProcess/medItkMultiplyImageProcess.h, src-plugins/medItkMultiplyImageProcess/medItkMultiplyImageProcessPlugin.h, src/medCore/gui/area/medAbstractArea.h, src/medCore/gui/area/medAbstractAreaPlugin.h, src/medCore/gui/medGuiLayer.h, src/medCore/process/arithmetic_operation/medAbstractAddImageProcess.h, src/medCore/process/arithmetic_operation/medAbstractArithmeticOperationProcess.h, src/medCore/process/arithmetic_operation/medAbstractDivideImageProcess.h, src/medCore/process/arithmetic_operation/medAbstractMultiplyImageProcess.h, src/medCore/process/arithmetic_operation/medAbstractSubtractImageProcess.h, src/medCore/process/medAbstractProcess.h, src/medCore/process/medProcessLayer.h
Use the DEFINE_SYMBOL target property to simplify exports MACROS
This allow to have the same MACRO indicating if the header is being include from inside the lib or from a client application, thus we can have only one ###Export.h file to defined the EXPORTS macro for all the target in medInria instead of having one for each lib / plugin.
=> Simplify symbol exports  for DLL

src/app/medInria/CMakeLists.txt, src/layers/CMakeLists.txt, src/layers/medComposer/CMakeLists.txt, src/layers/medCore/CMakeLists.txt, src/layers/medCoreLegacy/CMakeLists.txt, src/layers/medImageIO/CMakeLists.txt, src/layers/medLog/CMakeLists.txt, src/layers/medPacs/CMakeLists.txt, src/layers/medRegistration/CMakeLists.txt, src/layers/medTest/CMakeLists.txt, src/layers/medVtkInria/CMakeLists.txt, src/layers/medVtkInria/vtkImageView/vtkImageView2D.cxx, src/plugins/legacy/itkDataImage/CMakeLists.txt, src/plugins/process/arithmetic_operation/medItkAddImageProcess/CMakeLists.txt, src/plugins/process/arithmetic_operation/medItkDivideImageProcess/CMakeLists.txt, src/plugins/process/arithmetic_operation/medItkMultiplyImageProcess/CMakeLists.txt, src/plugins/process/arithmetic_operation/medItkSubtractImageProcess/CMakeLists.txt, src/plugins/process/morphomath_operation/medItkClosingImageProcess/CMakeLists.txt, src/plugins/process/morphomath_operation/medItkDilateImageProcess/CMakeLists.txt, src/plugins/process/morphomath_operation/medItkErodeImageProcess/CMakeLists.txt, src/plugins/process/morphomath_operation/medItkOpeningImageProcess/CMakeLists.txt
Simplify CMakeLists by avoiding us to manually manage all the medFoo_INCLUDE_DIRS variables. 
See : https://cmake.org/cmake/help/v3.2/command/target_include_directories.html
Fix some path issues with qtcreator for auto-completion.
=> Use target_include_directories feature.

src/layers/legacy/medVtkInria/vtkDataManagement/vtkMetaDataSetSequence.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
BugCorrection #292
Two bugs are fix:
Some view interaction glitches: for example drop the 4d image of the heart, then the heart mesh. If you interact with the view, it will change the window level of the first layer (image) even though the mesh is selected on the right. In addition if that view is linked to others (eg do a 4 view split after dropping the two data), then this window leveling is not synchronized with the others
Drop the 4d heart image, switch to 3d mode, click on play in the navigator -> the image doesn't move. It does work in 2d but not 3d anymore...
Correction consists of:
-replace SetInputData by SetInputConnection;
-Create an individual windowLevel filter for x,y,z actors.
=> View bug correction with good base

src/CMakeLists.txt, src/layers/legacy/medCoreLegacy/parameters/medTimeLineParameterL.cpp, src/layers/legacy/medVtkInria/CMakeLists.txt, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h, src/plugins/legacy/itkDataImage/CMakeLists.txt, src/plugins/legacy/itkDataImage/navigators/medVtkViewItkDataImageNavigator.cpp, src/plugins/legacy/medVtkView/medVtkView.cpp, superbuild/CMakeLists.txt, superbuild/projects_modules/VTK.cmake, superbuild/projects_modules/medInria.cmake
Correction of 4 bugs from #292 :
- Once you've seen your data in VR, changing the orientation is quite slow, slicing is very slow. It's also happened to me since I am using VTK7 in MUSIC.
- Remove deprecated VTK VR modes
- Add new VTK VR modes if they are available
- In 4D volume, in visualization mode, when time is set manually, if you press 'play' button, it start playing at the first 3D volume.
BECAREFULL !!! Create a dependency on OSPRay external library.
=> VR and vtk perf

.gitignore, src/app/medInria/medDiffusionWorkspace.cpp, src/app/medInria/medFilteringWorkspace.cpp, src/app/medInria/medFilteringWorkspace.h, src/app/medInria/medRegistrationWorkspace.cpp, src/app/medInria/medSegmentationWorkspace.cpp, src/app/medInria/medVisualizationWorkspace.cpp, src/app/medInria/medVisualizationWorkspace.h, src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp, src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.h, src/layers/legacy/medCoreLegacy/gui/medRootContainer.cpp, src/layers/legacy/medCoreLegacy/gui/medRootContainer.h, src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.cpp, src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.h, src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBox.cpp, src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBoxBody.cpp, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainerSplitter.cpp, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainerSplitter.h, src/layers/legacy/medCoreLegacy/medPluginManager.cpp, src/layers/medCore/job/medJobManager.cpp, src/layers/medCore/job/medJobManager.h
- "Generic, filtering and diffusion workspaces probably do something wrong when loading plugin processes or handling them: when quitting the app after using one plugin in those workspaces, there is a crash" by mikejbuckingham
- "Sometimes a crash happens when quitting medinria related to views and tabbed views deletion. Replicating this will do it : open medinria, load a first layer with an image, then add a mesh on top of it. Now close the app and the crash happens" by ocommowi
Improve multi-tabs into filtering workspace. 
- split toolBoxe of creation of new filter and parameter of it in 2 different.
- Improve robustness of toolBoxes placing and displaying.
=> Workspaces improvement

src/app/medInria/medQuickAccessMenu.cpp, src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medStartupSettingsWidget.cpp, src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medStartupSettingsWidget.h
Bug correction from issues #292 settings can be inconsistent due to "Generic" is enable or disable:
- bug "If visu workspace selected as default in settings, going to segmentation when opening the app or even crashing in some cases"  reported by ocommowi
=> Inconsistent settings

src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainerSplitter.cpp
Correction of glitch transparency on a view after a containerSplitter removing.
Correction of a bug of view position after a containerSplitter removing.
=> Correction of glitch and bug on views into containerSplitter

src/layers/legacy/medCoreLegacy/database/medDataManager.cpp, src/layers/legacy/medVtkInria/vtkImageView/vtkImage2DDisplay.cpp, src/layers/legacy/medVtkInria/vtkImageView/vtkImage2DDisplay.h, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.h, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
- Correction of crashing bug when medInria closing after a set in first fibers and after over the fibers a volume. The bug is due to dtklog.
- Correction  issuses #318 "The pixel value in a layered view of medinria is always linked to the first layer. Even if the second layer of a view is selected."
=> Improvements and small corrections

superbuild/projects_modules/QtDCM.cmake, superbuild/projects_modules/RPI.cmake, superbuild/projects_modules/TTK.cmake, superbuild/projects_modules/dtk.cmake, superbuild/projects_modules/dtkImaging.cmake, superbuild/projects_modules/medInria.cmake
(From https://github.com/Inria-Asclepios/medinria-superproject/pull/64)
This PR removes the `-Wno-inconsistent-missing-override` warning on Linux.
:m:
=> [music3] remove Wno-inconsistent-missing-override warning

packaging/apple/ApplePackScript.cmake.in, packaging/linux/LinuxPackaging.cmake, packaging/unix/Launchers.cmake, packaging/windows/WindowsLaunchers.cmake, packaging/windows/WindowsPackaging.cmake, superbuild/CMakeLists.txt
In MUSIC 2 we have various private plugin repositories, and setting up a working MUSIC development environment is impractical. Each private set of plugins must be cloned separately, and each has its own superproject which needs to be configured with the path to the medInria superproject, and inversely the medInria superproject needs to be configured with the path of the private plugins to load them.
It is much simpler to remove the plugin superprojects and set them up as external projects, so that medInria handles their configuration automatically. I did this successfully with the main MUSIC plugins repo, and it requires the addition of a cmake variable `EXTERNAL_PROJECT_PLUGINS_LEGACY_DIRS` that allows external project configuration files to add the path of their plugins.
_(The inclusion …
=> External project plugins

src/CMakeLists.txt, src/cmake/medInriaConfig.cmake.in, src/layers/legacy/medVtkDataMeshBase/CMakeLists.txt
Some changes required for the MUSIC plugins:
- Provide include path variables for medUtilities and medVtkDataMeshBase
- Add medUtilities and medVtkDataMeshBase to the config file
- Link ITK libs for medVtkDataMeshBase
=> Fixes for MUSIC plugins

src/app/medInria/areas/workspaces/diffusion/medDiffusionWorkspace.cpp, src/layers/medCore/process/diffusion_processes/medDiffusionModelEstimationMetaProcess.cpp, src/layers/medWidgets/process/diffusion_processes/medDiffusionModelEstimationMetaProcessPresenter.cpp, src/layers/medWidgets/toolboxes/medDiffusionSelectorToolBox.cpp, src/layers/medWidgets/toolboxes/medDiffusionSelectorToolBox.h
The toolboxes opened when the Diffusion workspace is open were too large. It should fit in the minimum size of the column.
:m:
=> [Diffusion] toolboxes were too large

src/app/medInria/areas/composer/medComposerArea.cpp
In the Composer workspace, two buttons were not enough large to show their title.
:m:
=> [Composer] solve fixedSize of 2 buttons

packaging/windows/WindowsLaunchers.cmake, src/CMakeLists.txt, superbuild/projects_modules/medInria.cmake
- Remove issues #386 warning ITK_LEGACY_REMOVE
- On VisualStudio make medInria as startup project into medInria Solution
- On VisualStudio for medInria superbuil solution make a post build event for medInria project to hardlink DLLs dependencies.
=> - Remove issues #386 and enhance startup capability for VS2017  

src/app/medInria/medMainWindow.cpp, src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
Resolve issues: Command-line view infinite-loops with bad filepath #228
Resolve issues: "CRASHING BUG, when you open an image via the command line like "--view toto.nii.gz", on Windows and Linux not on OSX." of Rest of bug and bad behavior in release 3.0 of medInria #335 (this part is go into #413)
fix #228
fix #413
=> Resolve 2 crashing bugs from cli and open file

src/app/medInria/medMainWindow.cpp, src/app/medInria/medMainWindow.h
Commit: https://github.com/medInria/medInria-public/commit/77a42ed719e0bb8c67f159e2cad3d5eae7f53455
Original PR: https://github.com/Inria-Asclepios/medInria-public/pull/507
`If the user clicks on one of the exit buttons, a message dialog is displayed to validate the exit. If the database has temporary data, the classic medSaveModifiedDialog pop-up is displayed instead.`
:m:
=> [music3] add a pop-up to validate exit

src/layers/legacy/medUtilities/medUtilities.cpp
From PR https://github.com/Inria-Asclepios/medInria-public/pull/582
> crash when call to to switchTo3D
> mode3DParam and renderer3DParam could not have not been initialized.
:m:
=> [music3] medUtilities empty variable crash solved

src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
From this PR https://github.com/Inria-Asclepios/medInria-public/pull/569
The original problem in some Linux drivers seems to be removed since Ubuntu 18. It was there on Ubuntu 16 on X.org drivers, not nvidia. On Ubuntu, these driver names have changed, and always start with "Intel". 
The non-offscreenCapable algo in this medAbstractData::generateThumbnail creates a pop-up when you save a data in a toolbox for instance. So, using the offscreenCapable removes it.
:m:
=> [music3] generateThumbnail - remove pop-up at import in DB

src/app/medInria/medMainWindow.cpp, src/plugins/legacy/vtkDataMesh/navigators/vtkDataMeshNavigator.cpp, src/plugins/legacy/vtkDataMesh/navigators/vtkDataMeshNavigator.h
From https://github.com/Inria-Asclepios/medInria-public/pull/348
The user can change the background color of a mesh from a list of color. The color background is kept when the user export screenshots of the view(s). There is a default name and filter for the screenshots.
:m:
=> [music3] change the background color - kept in screenshots

src/layers/legacy/medCoreLegacy/views/medAbstractLayeredView.h
From https://github.com/Inria-Asclepios/medInria-public/pull/502
Commit: https://github.com/medInria/medInria-public/commit/aec11005558657846d70b134ffbef323966e5d80
> Add templated method in medToolBox to retrieve a specific interactor from layered views.
:m:
=> [music3] add method to retrieve a specific layer interactor

src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
From https://github.com/Inria-Asclepios/medInria-public/pull/193
> In visualization, switch to 4 views, scroll with the mouse -> freeze between 2 slices
> The problem was caused by a loop in the slots being called.
:m:
=> [music3] medVtkViewItkDataImageInteractor - fixes scroll bug in 4-window view

src/layers/legacy/medCoreLegacy/database/medDatabaseModel.cpp, src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp, src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h
Commit https://github.com/medInria/medInria-public/commit/6a928f6dbd19390355ed07a8e63421a577da0de6
From https://github.com/Inria-Asclepios/medInria-public/pull/256
> Allow to drop a study in a view, or right-click->View on a study to open the series list in a view.
If more than 10 data are going to be opened, a validation pop-up asks the user if he/she wants to open it. It avoids "mis-drops".
:m:
=> [music3] DB - open a study with several series in a view 

src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.cpp, src/layers/legacy/medUtilities/mscTransform.h, src/plugins/CMakeLists.txt, src/plugins/legacy/medVtkView/medVtkView.cpp, src/plugins/legacy/reformat/CMakeLists.txt, src/plugins/legacy/reformat/medCropToolBox.cpp, src/plugins/legacy/reformat/medCropToolBox.h, src/plugins/legacy/reformat/medReformatWorkspace.cpp, src/plugins/legacy/reformat/medReformatWorkspace.h, src/plugins/legacy/reformat/medResliceViewer.cpp, src/plugins/legacy/reformat/medResliceViewer.h, src/plugins/legacy/reformat/reformatPlugin.cpp, src/plugins/legacy/reformat/reformatPlugin.h, src/plugins/legacy/reformat/reformatPlugin.json, src/plugins/legacy/reformat/reformatPluginExport.h, src/plugins/legacy/reformat/resampleProcess.cpp, src/plugins/legacy/reformat/resampleProcess.h, src/plugins/legacy/reformat/resliceToolBox.cpp, src/plugins/legacy/reformat/resliceToolBox.h
This PR adds:
* the Reformat workspace, 
* the Crop toolbox to "crop" data,
* the Reslice toolbox to manually change the orientation and center of a data, and choose the data size and spacing.
The Reslice toolbox was a bit complicated to adapt because of VTK8 and the viewer we create. Thx to @Florent2305 which helped me (that's why there are commits from both of us).
edit: this PR is going to be rebased after the merge of the other linked PR
:m:
=> [music3] workspace Reformat, Crop tlbx and Reslice tlbx

src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
Because of a rebase error during the mix of Histogram, Four-split and Maximize changes in the Tools button of views, the maximize action was missing.
:m:
=> [Maximize] rebase error maximize action disappear

src/app/medInria/medMainWindow.cpp, src/app/medInria/medSplashScreen.cpp
On multiple screen display, if you close the application on screen 2 for instance, at the next opening, medInria will open on screen 2. But not the splash screen.
This PR solves the problem, and open the splash screen on the current screen.
:m:
=> [Splash] center on previous current screen

src/app/medInria/resources/authors.html
From https://github.com/medInria/medInria-public/issues/433
This is a suggestion for the authors lists (seen with @Florent2305 and @msermesant ) which can be updated if needed.
I added the music developers to this list, with the project(s) affiliated. Some people have multiple linked projects.
As done on our side, i put only first and last names on this list, because a lot the emails are deactivated. If needed, the users need to use the contact mail. And the list has more readability like that. This is a suggestion, and can be changed if needed.
:m:
=> [Authors] add music dev to author list

src/plugins/legacy/polygonRoi/polygonRoiToolBox.cpp
Fix the crash:
* Drop a data in a view, open PolygonROI
* Draw a ROI, delete it (with the "D" button in medRoiManagementToolbox)
* Switch to an other toolbox (Paint for instance) -> crash
:m:
=> [PolygonROI] crash delete roi and switch to other tlbx

src/layers/legacy/medCoreLegacy/data/medAbstractDataWriter.cpp, src/layers/legacy/medCoreLegacy/data/medAbstractDataWriter.h
In order to use some plugins from music to export files, we need a writer for multiple files.
From https://github.com/Inria-Asclepios/medInria-public/commit/3123af16e6351f4f2c7893d616338f2df0966d98#diff-f83dafefecba1af52646e8b9758252fc and https://github.com/Inria-Asclepios/medInria-public/commit/b6384f1b573582a3696aadb6060dc66b5bccb810#diff-f83dafefecba1af52646e8b9758252fc
:m:
=> [medAbstractDataWriter] add files to export list of data

src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsPlugin.h, src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsPluginExport.h
Standardize the export file for Windows compilation. It could prevent also compilation errors.
:m:
=> [diffeo] standardize export file for windows

src/plugins/legacy/medN4BiasCorrection/CMakeLists.txt, src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionToolBox.cpp
Fix compilation and link error when building on macosx.
__medN4BiasCorrection Plugin__  
- Add missing std include in file. 
- Add ITK_LIBRARIES in CMakelists.txt => target_link_libraries
=> [MACOSX - FIX] - medN4BiasCorrection - build and link errors

src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImage4DInteractor.cpp, src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp, src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h, src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp, src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
This PR aims to clean/solve remaining problems seen in Variational Segmentation from the interactors system.
* No crash closing the last layer of the view in the toolbox
* Slicing Parameter standardize in interactors
And something weird in varSegToolBox.cpp:
if you do not save the output data in the db (with `VarSegToolBox::addBinaryImage`) before adding the output in the view, it crashes. During this crash, `medVtkViewItkDataImageInteractor::setInputData` is called, but does not succeed to do `SetViewInput (data, d->view->layer(data)`.
I have got a `"Unable to add data:  \"itkDataImageUChar3\"  to view  \"medVtkViewItkDataImageInteractor\""` warning.
Thus, the data is not really created, including parameters which create the crash. 
In this PR, since we want to do an alpha release soon, …
=> [VariationalSeg] interactors cleaning

src/app/medInria/main.cpp, src/app/medInria/medSplashScreen.cpp
Based on https://github.com/medInria/medInria-public/pull/441 (will be rebased)
COMMIT https://github.com/medInria/medInria-public/commit/578dcf8bbd50edb585b471ca34b55ebb45887014
Change the splash screen logo to the medInria homepage logo, which is... less.. orange? (:D) 
We would have a better readability of the text, and the logo is a rectangle, so, no transparency problems anymore. I think this "homepage" logo has more style than the orange original splash screen.
Example of this new splash screen:
:m:
=> [Splash] solve corner transparency pb, change logo

src/layers/legacy/medCoreLegacy/database/medStorage.cpp
On OSX, Replace the default DB path below  : 
- `/Users/account_name/Library/Application SupportmedInria`
with
- `/Users/account_name/Library/Application Support/inria/medInria/`
**CAUTION**, 
If you have already launch medInria on your laptop, 
the wrong db path is defined in your plist 
cf. key `database.actual_database_location` in file `/Users/account_name/Library/Preferences/com.fr.medInria.plist`
and the fix does not work.
**First, You have to delete the key from your plist**
1. Open a terminal
2. `defaults delete com.fr.medInria database.actual_database_location`
=> [FIX] - [OSX] - default db path

src/app/medInria/main.cpp, src/app/medInria/medApplication.cpp
From work with @Florent2305. No need to register already registered QVariant type (Quuid). Move medDataIndex register in medApplication.
:m:
=> [qRegisterMetaType] clean qt metatype register at app opening

RELEASE_NOTES.txt, src/CMakeLists.txt
Fixes https://github.com/medInria/medInria-public/issues/433
This PR updates the release notes file with the changes in the future 3.1 version of medInria. It can be updated until the release, if we had or remove tools/toolboxes/plugins/fix, etc. Specially for the Filtering Legacy workspace.
=> [RELEASE_NOTES] update the release notes with 3.1 changes

src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp, src/layers/legacy/medCoreLegacy/medPluginManager.cpp
This PR:
* clean the logs at run of medInria
* avoid "Your config does not seem to be set correctly." warning in logs
* fixes https://github.com/medInria/medInria-public/issues/468 removing an empty file
:m:
=> [Logs] avoid warning message, and qprintable

src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
Fixes https://github.com/medInria/medInria-public/issues/230
On close, if you want to save temporary data, the code checks if there is already a data with the same name in the database, and add a suffix on the name.
(it was an issue for 4.0 but it was a quick fix, and i worked a lot of these code since few week, so i was not lost)
:m:
=> [DB] save-on-quit save temporary data: no duplicated names

src/app/medInria/areas/composer/medComposerArea.cpp
Fixes https://github.com/medInria/medInria-public/issues/437
This PR removes the composer menubar which was displayed in each workspace. It's clearer for users, and avoid problems if the users click on the menu items in an other workspace.
:m:
=> [Composer] menu become QtoolButton, not application menubar

src/app/medInria/main.cpp
This PR removes the arg warning when we launch medInria with `--debug` parameter.
:m:
=> [Run] avoid debug warning at app launch

src/plugins/legacy/reformat/medResliceViewer.cpp, src/plugins/legacy/reformat/medResliceViewer.h, src/plugins/legacy/reformat/resliceToolBox.cpp
Based on https://github.com/medInria/medInria-public/pull/512, will be rebased.
Fixes https://github.com/medInria/medInria-public/issues/509
Remove the crash using the reslice toolbox. This was from an incorrect input, and a wrong connection.
COMMIT:  https://github.com/medInria/medInria-public/commit/0ae6260f552631ef19e311f87007cf824f6581a4
:m:
=> [Reslice] solve crash using reslice toolbox

src/app/medInria/medQuickAccessMenu.cpp
Should fixes https://github.com/medInria/medInria-public/issues/515
The default workspace number is not 0, it's 1 (homepage).
Is it possible to test it @Florent2305 on the computer on which you had the bug? If you want to test quickly, you just need to change `int iRes = 0;` to `int iRes = 1;` in `medQuickAccessMenu` function `retrieveDefaultWorkSpace`. @mjuhoor had only once this bug. At the second opening of medInria, the search toolbox was not displayed at start.
:m:
=> [SearchToolbox] open at app start on some pc

src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp, src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.h, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx, src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Working on https://github.com/medInria/medInria-public/issues/492 i enhanced the way the steps are computed for min and max intensities sliders.
Edit: this PR helps solving https://github.com/medInria/medInria-public/issues/492. It needs to be tested on an other PC however i think. On mine, this is really quicker, especially because of `d->view2d->SetColorWindowLevel(window, level, layer);` in `medVtkViewItkDataImageInteractor::setWindowLevelFromMinMax()`.
:m:
=> [DataInteractor] min/max intensities steps

src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
In order to see the bug:
* Open medInria -> Settings -> Database -> change the database path to a completely new one -> Save -> Close medInria
* Open medInria -> Workspace/Browser -> open a data -> permanent saving of the data -> Close medInria
* Open medInria -> Visualization -> open the data: it does not open.
This PR solves this problem. New databases were not opened well, since the image column does not exist in them, but user_version is not set.
:m:
=> [DB] avoid not-found saved data in a new database after restart

src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
Fixes the bug discussed in https://github.com/medInria/medInria-public/pull/522
Only point and cell data should be displayed in the VTK attributes combobox. This fix allows us to load images generated by MUSIC 2 without metadata tags being displayed in the attributes list.
_Note that cell data is not actually handled, only point data (see link below) but that is a separate issue:
https://github.com/medInria/medInria-public/blob/master/src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp#L397_
=> Remove generic field data from VTK attributes combo

src/plugins/legacy/vtkDataMesh/readers/vtkDataMesh4DReader.cpp, src/plugins/legacy/vtkDataMesh/readers/vtkDataMesh4DReader.h, src/plugins/legacy/vtkDataMesh/readers/vtkDataMeshReader.cpp, src/plugins/legacy/vtkDataMesh/readers/vtkDataMeshReader.h, src/plugins/legacy/vtkDataMesh/readers/vtkDataMeshReaderBase.cpp, src/plugins/legacy/vtkDataMesh/readers/vtkDataMeshReaderBase.h, src/plugins/legacy/vtkDataMesh/writers/vtkDataMesh4DWriter.cpp, src/plugins/legacy/vtkDataMesh/writers/vtkDataMesh4DWriter.h, src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriter.cpp, src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriter.h, src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriterBase.cpp, src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriterBase.h
From a bug found by @mjuhoor  and @paulineMig, metadata were shown in attributes of a vtk in the Settings.
This PR allows to add metadata in a VTK file.
:m:
=> [vtk] write/read metadata in vtk mesh files at export/import

src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBoxTab.cpp
Small typo in medToolBoxTab with a nullptr.
:m:
=> [nullptr] small typo

src/layers/legacy/medCoreLegacy/data/annotationData/medImageMaskAnnotationData.cpp, src/layers/legacy/medCoreLegacy/gui/database/medDatabasePreview.cpp, src/layers/legacy/medCoreLegacy/gui/factories/medWorkspaceFactory.cpp, src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.cpp, src/layers/legacy/medCoreLegacy/gui/toolboxes/medSelectorToolBox.cpp, src/layers/legacy/medTest/medQtDataImageWriter.cpp, src/plugins/legacy/medVtkFibersData/interactors/medVtkFibersDataInteractor.cpp, src/plugins/legacy/polygonRoi/medRoiManager.cpp, src/plugins/legacy/polygonRoi/vtkInriaInteractorStylePolygonRepulsor.cxx
From a comment of @Florent2305 and according to the obsolete code of Qt : https://doc.qt.io/qt-5/qtalgorithms-obsolete.html#qSort-2
Switch qSort to std::sort.
:m:
=> [Deprecated] qSort -> std::sort

src/plugins/legacy/itkDataSHImage/CMakeLists.txt, src/plugins/legacy/itkDataSHImage/interactors/itkDataSHImageVtkViewInteractor.cpp, src/plugins/legacy/itkDataSHImage/management/vtkSphericalHarmonicSource.cxx, src/plugins/legacy/itkDataSHImage/readers/itkDataSHImageReader.cpp
Corrects two problems:
- MaxSH basis was not fitting the one from M Descoteaux PhD, corrected
- SH images were required to be of order less than 6, not a limit anymore
- Reading SH images on my computer was failing on med 3.1.1 future version, corrected
To be merged also to medinria3.1.x branch
=> Spherical harmonics corrections

src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageViewCornerAnnotation.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageViewCornerAnnotation.h
Solve 2 annotations problems on 3.1: the "Zoom:" text was not written, and the slice/slice_max not updated.
I'm going to test on master and do the same PR if needed.
:m:
=> [Annotation] slice numbers and zoom txt

src/layers/legacy/medImageIO/itkGISImageIO.h, src/layers/legacy/medImageIO/itkGISImageIOFactory.h, src/plugins/legacy/itkDataImage/readers/itkDataImageReaderCommand.cpp
Remove cstddef includes which are not used anymore, and indent the class.
:m:
=> [cstddef] remove unused include & indentation

src/plugins/legacy/polygonRoi/data/polygonRoi.cpp, src/plugins/legacy/polygonRoi/data/polygonRoi.h, src/plugins/legacy/polygonRoi/medTagRoiManager.cpp, src/plugins/legacy/polygonRoi/medTagRoiManager.h, src/plugins/legacy/polygonRoi/polygonEventFilter.cpp, src/plugins/legacy/polygonRoi/polygonEventFilter.h, src/plugins/legacy/polygonRoi/polygonRoiToolBox.cpp, src/plugins/legacy/polygonRoi/repulsor/vtkInriaInteractorStylePolygonRepulsor.cxx
- Fix: Crash 
- Open data in tb, create a contour, close tb, then reopen a data, activate tb ==> crash
- Fix: Open a contour file (.ctrb) saved on disk
- Ability to create a contour very closed to another one without modifying it.
- Enhancement: rename a label and validate with Enter Key
- Fix: No events are possible on contours while tb is deactivated
- Fix: contextual menu superposition on windows
- Enhancement: Keep repulsor after changing slice
- Enhancmeent: Keep label active after changing slice
=> Feedback APHP

src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
Fixes https://github.com/medInria/medInria-public/issues/579
Allow to display meshes in 3D.
The commit involved in the problem: https://github.com/medInria/medInria-public/commit/f0bb709d35ae71c91ce773b13e3ac708b9002423
I have a question @Florent2305 : the changes of the commit were not applied on the master branch. It may be a merge problem because in the [3.1.1 commit list](https://github.com/medInria/medInria-public/commits/medInria3.1.x) you have a few commits later an [other commit](https://github.com/medInria/medInria-public/commit/14d03ec53463299f7b9af1e0d501ee23b7b549bd) applying the same change. If your changes were needed to solve a mesh/fiber issue, it's still needed to be apply on the master branch, or it could be a merge problem and this PR solves it.
:m:
=> [Meshes] solve meshes not seen in 3D

src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSet.cxx, src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.cxx, src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.h, src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.cxx, src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx, src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp, src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.h
- Fix the displayed attribute's range (called intensity in the code). The min and max values are now computed across the whole sequence.
- For integer arrays, intensity step will be 1 and number of decimals 0.
=> [4D mesh] Fix attribute intensity problem

src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
Suggestion to have a deeper debug to the problem found by @nbaraka in https://github.com/medInria/medInria-public/pull/602
InternalUpdate is already called after SetOtherLayer, so, no need to called it again. And the second call created the crash.
:m:
=> [nrrd/nhrd/nrrd] debug crash opening Nordine data

src/app/medInria/QSingleApplication/qtsingleapplication.cpp, src/app/medInria/QSingleApplication/qtsingleapplication.h, src/app/medInria/medSplashScreen.cpp, src/layers/legacy/medCoreLegacy/CMakeLists.txt, src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp, src/plugins/legacy/medVtkView/medVtkView.cpp
Working on an other problem, i found that Q_OS_X11 and qt_x11_wait_for_window_manager were in QT4 but are not in QT5.
I'm going to create the master one also.
:m:
=> [Q_OS_X11] changes from Qt4->5, code was not used

src/layers/legacy/medCoreLegacy/views/medAbstractView.cpp, src/plugins/legacy/medVtkView/medVtkView.cpp
Fix https://github.com/medInria/medInria-public/issues/608
Fix https://github.com/medInria/medInria-public/issues/593
Fix https://github.com/medInria/medInria-public/issues/630 (@nbaraka is it possible to check on your side?)
This PR puts back the thumbnail creation after a process in medInria, and remove the flickering bug on views.
I am going to create the master one.
:m:
=> [Views] remove flickering, add back thumbnails

src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp, src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Fix #621 Very Low Range image not usable (eg 0 to 0.005)
On 3.1.x
=> Correction of very low windowLevel images (range < 10^-2)

src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.cxx, src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx
- Medit surface and volume mesh are now properly read
- Implements a more robust check for medit file format, as the '.mesh' extension also exists for other file formats (i.e. Biosense Webster CARTO)
=> [medInria-3.1.x] Add support for medit .mesh file format

src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
Fix https://github.com/medInria/medInria-public/issues/595
The layer Group is in the layer menu, and the view Group is in the view menu. It's solved by the last line of this PR.
I removed a duplicated computation also in loops.
I'm going to do the master PR as well.
:m:
=> [Menu Links] Layer group 1 appears in link view properties

src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Solves https://github.com/medInria/medInria-public/issues/645
On Ubuntu at least, no ceill, fabsl, log10l.
:m:
=> [Ubuntu18.04] compilation ceill fabsl log10l

src/plugins/legacy/polygonRoi/data/polygonRoi.cpp, src/plugins/legacy/polygonRoi/data/polygonRoi.h, src/plugins/legacy/polygonRoi/medTagRoiManager.cpp, src/plugins/legacy/polygonRoi/medTagRoiManager.h, src/plugins/legacy/polygonRoi/polygonEventFilter.cpp, src/plugins/legacy/polygonRoi/polygonEventFilter.h, src/plugins/legacy/polygonRoi/polygonRoiToolBox.cpp, src/plugins/legacy/polygonRoi/polygonRoiToolBox.h, src/plugins/legacy/polygonRoi/repulsor/vtkInriaInteractorStylePolygonRepulsor.cxx
- Fix Interpolation checkbox always disable
- Add error management.
Errors are displayed in menu bar (as other tb)
- Activate a label
When a new label is created, the others become light gray and it is impossible to interact with.
A contextual menu (right click) allows user to activate another label
- the Cursor becomes an open hand if is close to a node. 
- contextual menu is displayed near a contour (instead of a node)
- left clic color menu is removed
=> Aphp feedback 

src/app/medInria/medDataSourceManager.cpp, src/app/medInria/medDataSourceManager.h, src/app/medInria/medFileSystemDataSource.cpp, src/app/medInria/medFileSystemDataSource.h, src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp, src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.cpp, src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.h, src/layers/legacy/medCoreLegacy/medAbstractDataSource.h
fix https://github.com/medInria/medInria-public/issues/580
* Remove the Bookmark button on the left panel, and keep it in right-click.
* Remove the Index button and right-click action.
* Debug double-click and View button, which does the same thing. The code was just commented, it was so weird XD.
* Right-click actions have the same order as the buttons in left panel, to avoid to lost the user.
I'm going to do the same PR on master branch.
:m:
=> [Browser] View, Index, dbl-click, Bookmark cleaning

src/plugins/legacy/reformat/medResliceViewer.cpp, src/plugins/legacy/reformat/resliceToolBox.cpp
When there is no parameters changes when switching between **space** and **dimension** then the parameters are not updated : **space** parameters are used in **dimension**.
=> solve #669 in parameters retrieving 

src/layers/legacy/medCoreLegacy/views/navigators/medAbstractImageViewNavigator.cpp, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h, src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp, src/plugins/legacy/itkDataImage/navigators/medVtkViewItkDataImageNavigator.cpp
Major bug : missing call to internalUpdate after a new layer is added. 
Some minor changes to reduce the number of function calls, remove unecessary line, improve the lut management by the scalar range : related #326 #657 ,2 images with big diff in their scalar ranges
In order to overcome the 4 layers limit I would like to change how the layer are managed in the volume rendering. 
With less perf. constraint, it might be possible to improve the rendering of the diff layers and to make the code easier to understand. Now layer index are related index of RGBV (difficult to understand but it seems to be a nice trick)
=> improve #326 and solve  #657 

src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Fix #581 [Tests] 3.1.1 and master -> once min/max intensities in 3D, it's kept
For 4.0
=> Fix #581 once min/max intensities in 3D V4.0

src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Fix #581 [Tests] 3.1.1 and master -> once min/max intensities in 3D, it's kept 
For 3.1.x
=> Fix #581 once min/max intensities in 3D V3.1.1

src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Names of the algos run were not shown anymore in the undo redo toolbox after running a registration algorithm. This corrects it. To be pushed on 3.1.x as well
=> Put back algo name in undo redo toolbox

src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Put back algo name in undo redo toolbox
Port of ocommowi:undo-redo-bug-corr for medInria V3.1.1
cf #693 Put back algo name in undo redo toolbox
=> Put back algo name in undo redo toolbox for medInria V3.1.1

src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Same as https://github.com/medInria/medInria-public/pull/700 on 3.1.1
Solve the compilation error with index named twice.
:m:
=> [Registration] undo-redo current tlbx name

src/plugins/legacy/LCCLogDemons/LCCLogDemons.cpp, src/plugins/legacy/LCCLogDemons/LCCLogDemons.h, src/plugins/legacy/LCCLogDemons/LCCLogDemonsToolBox.cpp, src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.cpp, src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp, src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp
Fixes https://github.com/medInria/medInria-public/issues/694
This PR:
* LCC uses the common processbar, not its own
* export of transformation does not crash
* avoid crashes using data with different spacings or sizes
* add explanation about data to use for users
* standardize the labels with the other Registration tlbx
* fill the getTitleAndParamaters label
* fix double output problem with Diffeomorphic toolbox
I'm not sure the exported transformation is right however, i did not test it.
I'm going to do the same PR on master too.
:m:
=> [LCC-LogDemons] avoid crashes (transfo, spacing, size), standardize

src/app/medInria/medLogger.cpp, src/app/medInria/medLogger.h
This PR change the way to redirect cout and cerr.
Now don't use **dtk** to redirect log but **Boost**
It avoids some crashs or freezes when external dependencies, like RPI, did a cout or cerr.
The problem is due to incorrect re-lock mutex inside dtklogger
cd https://github.com/medInria/medInria-public/issues/695
=> medLoggerRedirectWithBoost

src/plugins/legacy/polygonRoi/data/medContourSharedInfo.cpp, src/plugins/legacy/polygonRoi/polygonEventFilter.cpp, src/plugins/legacy/polygonRoi/toolboxes/contoursManagementToolBox.cpp
Fix bugs just before delivering binary to APHP
A ) Scenario:
1. Add a score to a pre-defined target in widget list  (target 1 or target 2 for instance)
2. delete it and re-create it without score.
3. Save contours
4. Load the saved contours 
==> The target was displayed with name `Target 1 - `
B ) Delete a predefined label with button minus (-)
The selected contour is delete in view but the name is in the widget list yet.
==> Clic on view ==> no color is selected and we were unable to create a new contour
=> [FIX] - Label name were lost at import in specific cases

src/plugins/legacy/polygonRoi/medTagRoiManager.cpp, src/plugins/legacy/polygonRoi/polygonEventFilter.cpp, src/plugins/legacy/polygonRoi/polygonEventFilter.h
1. Remove special characters ":" in description when a mask is saved to avoid issue on Windows
2. Add shortcut "a" to activate a contour on view
3. Remove unused lines (mousePos)
4. Remove go to slice when selected for contours named WG and TZ
=> Fix a syntax error when a mask is saved on disk (windows) + some details 

src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
before using mapDisplayToWorldCoordinates  with MouseEvent
compute the device Pixel Ratio and apply to mouse Position
=> [FIX] - Add PixelDeviceRatio for OSX Screen Retina

src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx, src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.cpp, src/plugins/legacy/medVtkView/medVtkViewNavigator.cpp
At the end of the 3.1.1 release i found some things to enhanced for 4.0. They were not an emergency for 3.1.1.
* some typos are removed in comments
* remove spaces in text in diffeomorphicDemons where it's not needed (as in LCCLogDemmons)
* added tooltips to the orientation buttons
:m:
=> [Various] typos and tooltips found

src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp, src/plugins/legacy/polygonRoi/polygonRoiToolBox.cpp, src/plugins/legacy/reformat/medCropToolBox.cpp, src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp, src/plugins/legacy/voiCutter/voiCutterToolBox.cpp
Avoid crashes if you try to open medVtkFibersData in some toolboxes.
:m:
=> [medVtkFibersData] avoid crashes opening fibers in tlbx

src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
- Fixes a bug where, if there is a volume and a mesh in the 2D view, changing the LUT of the mesh would also change the LUT of the image.
=> [vtkDataMeshInteractor] Fix mesh LUT messing with image LUT

src/plugins/legacy/polygonRoi/data/vtkContourOverlayRepresentation.cxx, src/plugins/legacy/polygonRoi/data/vtkContourOverlayRepresentation.h, src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
Cherry-pick of https://github.com/medInria/medInria-public/pull/758 on 3.1.1
This is a PR on the dev branch medInria3.1.x. There are no milestones for that.
:m:
=> [PolygonROI] problem with polygon world positions after double clicking --dev3.1

src/plugins/legacy/polygonRoi/data/vtkContourOverlayRepresentation.cxx
Context:
1. build medInria-public in Debug mode on macOs
2. open polygonROI Toolbox and try to draw a contour
==> Crash
In PR #764, We developed a hack to be able to compute the correct world position.
The call to the method  vtkInteractorObserver::ComputeDisplayToWorld(this->Renderer, displayPos[0], displayPos[1], 0.0, worldPos); cause a crash in the context described above.
The description of this method is:
```
//----------------------------------------------------------------------------
// Description:
// Transform from display to world coordinates.
// WorldPt has to be allocated as 4 vector
```
But the definition of the variable WorldPos passed as an argument in method was:
double WorldPos[3]
=> [FIX] - Var WorldPos has to be allocated as 4 vector

superbuild/projects_modules/VTK.cmake, superbuild/projects_modules/ffmpeg.cmake
After some full continuous integration compilations, switch ffmpeg to the n3.4.8 version (which, by the way, is the one used in apt versions in Ubuntu20).
:m:
=> [FFMPEG] switch to version n3.4.8

superbuild/external_projects_tools/EP_GeneratePatchCommand.cmake, superbuild/projects_modules/DCMTK.cmake, superbuild/projects_modules/ITK.cmake, superbuild/projects_modules/LogDemons.cmake, superbuild/projects_modules/QtDCM.cmake, superbuild/projects_modules/RPI.cmake, superbuild/projects_modules/TTK.cmake, superbuild/projects_modules/VTK.cmake, superbuild/projects_modules/dtk.cmake, superbuild/projects_modules/dtkImaging.cmake, superbuild/projects_modules/ffmpeg.cmake
The ALWAYS_BUILD cmake parameter is set to 0 on projects modules, except medInria. It avoids a complete recompilation each time you compile.
The patch_command and "if (NOT DEFINED ${ep}_SOURCE_DIR)" avoids some patch problems seen on some computers.
:m:
=> [CMake] avoid complete recompilation and patchs problems (on mac for instance)

src/plugins/legacy/itkDataImage/writers/itkNiftiDataImageWriter.cpp, src/plugins/legacy/itkDataImage/writers/itkNiftiDataImageWriter.h
-impose extension .nii before .nia because medinria can not read .nia
=> [NiftiDataImageWriter]: impose extensions order

src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
- Fixes #806
**This is a quick fix that does not adress the underlying problem.**
Simplified description of the issue:
When looking for files to import, medInria creates a temporary 'unique' identifier for each image series: if `n` files have the same identifier then they are part of the same series.
This identifier is a concatenation of multiple values of metadata, like patient name, series description, slice thickness, rows, columns... and orientation
The problem is that floating point values (like orientation) can have small variations in each DICOM files: this creates different identifiers for the same image series.
The issue was thought 'solved' previously, as evidenced by the comments in the code. 
I personally believe that we should be creating an identifier using other metadata, …
=> [DICOM import] Quick fix for creation of multi series from unique series

src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h
- Fixes #757 , so it seems
Instanciating a QString with no parameters and "" (empty string) is not the same thing. This seems important when querying the database for existing studies, patients, etc.
Does this change impacts other areas of the code ?
=> [Database importer] Fix creation of multiple clones of the same study when importing.

src/plugins/legacy/LCCLogDemons/LCCLogDemonsPlugin.cpp, src/plugins/legacy/LCCLogDemons/LCCLogDemonsPlugin.h, src/plugins/legacy/LCCLogDemons/LCCLogDemonsToolBox.cpp, src/plugins/legacy/LCCLogDemons/LCCLogDemonsToolBox.h, src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusPlugin.h, src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusToolBox.cpp, src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusToolBox.h
The Help buttons in the Optimus and LCC Log Demons toolboxes were not working. The plugin name called in the toolbox needs to be the same as the plugin name declared in the plugin files.
:m:
=> [Help Buttons] buttons on Optimus & LCC tlbx were not working

packaging/apple/mac_packager.sh.in
- Fixes #816 
- Increase size of sparse image when packaging on macOS
=> [macOS packaging] Increase size of sparse image

src/layers/legacy/medCoreLegacy/views/navigators/medAbstractImageViewNavigator.cpp, src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.cxx
-The number of frame rate was not compute as it should. Creating a shift of 1 frame on the time interactor
-Fix frong computation of time for each metadataset
=> [MetaDataSetSequence]: fix wrong sequence duration and number of timeStep

src/cmake/module/set_plugin_install_rules.cmake
Solve a packaging problem on Ubuntu due to https://github.com/medInria/medInria-public/pull/802 with .so files from medInria plugins which were removed before packaging.
:m:
=> [Package] solve packaging pb on Ubuntu with .so files

src/app/medInria/areas/workspaces/medWorkspaceArea.cpp, src/app/medInria/areas/workspaces/medWorkspaceArea.h, src/app/medInria/medMainWindow.cpp, src/layers/legacy/medCoreLegacy/gui/factories/medWorkspaceFactory.cpp, src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
This PR adds the possibility to handle workspace construction failure.
If an (unrecoverable) error is encountered in the constructor, it should throw an exception. This will be caught and handled by the workspace factory. The switch to the workspace will be cancelled and medInria will switch to the home area instead. To make sure resources are properly freed, a dedicated "parent" widget is given to the workspace so that all qwidgets it has created can be destroyed easily.
=> Handle workspace construction failure

src/layers/legacy/medCoreLegacy/gui/factories/medWorkspaceFactory.h
The non-templated version of registerWorkspace was protected. This PR makes it public so that workspaces can register their own creator.
(GitHub is not displaying the changes correctly. The only code that moved is the registerWorkspace method)
=> Allow non-standard workspace registration

src/plugins/legacy/itkFilters/itkFiltersComponentSizeThresholdProcess.cpp, src/plugins/legacy/itkFilters/itkFiltersComponentSizeThresholdProcess.h, src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
add option to binarize or not the filter output. Can be useful to keep an image labeled by components size.
=> [ComponentSizeThresholdFilter]: add option to binarize the ouput or not

src/cmake/module/set_lib_install_rules.cmake
The `headers_list` argument is not used and prevents calling this macro on libs that do not have associated headers (which is the case for bindings libraries).
=> set_lib_install_rules: remove useless headers_list

src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.cpp, src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.h, src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.cpp, src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.h, src/plugins/legacy/meshManipulation/meshManipulationToolBox.cpp
Add an option to get the transformation matrix of an iterative closest point process. 
Use it to transfer points from a patient to another.
=> [iterativeClosestPoint] Add Export Transformation Matrix Option

src/app/medInria/areas/homepage/medHomepageArea.cpp, src/app/medInria/resources/authors.txt, src/app/medInria/resources/medInria.qrc, src/doc/css/medInria.css
The "Developer" title on the Author tab was a bit strange when you look at the other tabs: release notes, licenses, etc. I looked at this file because it created also 2 html Sonarqube bugs, since the file was not completely how an html should be.
:m:
=> [Authors] txt file to fit the other (licence, release notes, etc) & solve Sonarqube error

src/CMakeLists.txt, src/app/medInria/CMakeLists.txt, src/cmake/module/add_external_resources.cmake, src/cmake/module/set_exe_install_rules.cmake, src/cmake/module/set_lib_install_rules.cmake, src/layers/legacy/medCoreLegacy/medExternalResources.cpp, src/layers/legacy/medCoreLegacy/medExternalResources.h
This PR adds a macro called`add_external_resources` to allow the addition of resources as separate files, and a function `med::getExternalResourcePath` to retrieve the resources at runtime. Resources can be added as part of the main application or for a specific library. They are handled differently depending on the OS:
**macOS**
Application-level resources are located in the bundle's resource folder. For library-level resources, the library is turned into a framework that will contain the resource. This works for both the build environment and the final package.
To access framework contents at runtime we need a reverse-DNS style identifier. A `${PROJECT_NAME}_IDENTIFIER` variable is set to `fr.inria.medInria` and serves as a prefix for the library identifiers (when built as frameworks). …
=> Add possibility to specify and load external resources

src/CMakeLists.txt, src/app/medInria/CMakeLists.txt, src/cmake/module/add_external_resources.cmake, src/cmake/module/set_exe_install_rules.cmake, src/cmake/module/set_lib_install_rules.cmake, src/layers/legacy/medCoreLegacy/medExternalResources.cpp, src/layers/legacy/medCoreLegacy/medExternalResources.h
(based on https://github.com/medInria/medInria-public/pull/848)
(adds commit https://github.com/medInria/medInria-public/commit/e331d189761c23b04e2349c74d5bdd7a44ca3607)
This PR extends the `add_external_resources` macro with an option to compile a set of resources into an external Qt binary resource file (rcc). This allows the resources to be registered with Qt's resources system so that they can be used exactly the same way as compiled-in resources.
=> [add_external_resources] option to generate RCC files

src/plugins/legacy/meshManipulation/meshManipulationToolBox.cpp, src/plugins/legacy/meshManipulation/meshManipulationToolBox.h
- Add undo, redo functionality to mesh manipulation
- Robustify import mechanism of matrices, i.e. won't crash when importing something else than perfectly formatted matrices
- Imported matrices will be shown in a list
- The applied transformation matrix is saved in the data itself (in vtk FieldData). This was already done for EPmaps.
- These saved matrices are retrieved automatically and displayed in the list
- Users can apply the inverse of the imported transformation matrices
=> [MeshManipulation] Undo redo and transformation list

src/layers/legacy/medUtilities/statsROI.cpp
From a compilation from scratch i saw a warning `ignoring return value of 'bool std::vector<_Tp, _Alloc>::empty() const [with _Tp = double; _Alloc = std::allocator<double>]', declared with attribute nodiscard [-Wunused-result]`. 
The call to `this->computedOutput.empty();` is wrong because it does not clear the vector (we should use `clear()` instead), it only tests if the vector is empty or not. However, here, it is not needed to test if the vector is empty, or to clear it, so i removed the line.
:m:
=> [StatsROI] useless call to empty()

src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSet.cxx, src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSet.h
In AddArray a register is called to increase the reference count on the vtkObject. 
LookUpTable is never deleted.
=> memory leak in vtkMetaDataSet

src/layers/legacy/medImageIO/vtkItkConversion.tpp, src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImage4DInteractor.cpp
Should find a way to make it more obvious (in vtkItkConversion)  to the developer  with a specific pattern in the function name or to use smart pointer (better sol). 
I do not have 4D data. if someone can send me a small data I will be happy to test it. 
I have check that in vtkImageView a deep copy is done the matrix and here it becomes a smart pointer.
=> memory leak, the caller is the owner 

src/layers/legacy/medCoreLegacy/gui/medTableWidgetChooser.h, src/plugins/legacy/polygonRoi/polygonEventFilter.cpp, src/plugins/legacy/polygonRoi/toolboxes/contoursManagementToolBox.cpp, src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
Fix https://github.com/medInria/medInria-public/issues/791
Fix https://github.com/medInria/medInria-public/issues/720
I wanted to solve the 2 bugs from the issue 791 in PolygonROI:
* Open a data, split the view with the orientation buttons, close the first view -> crash
* The orientation buttons have a glitch, they are cut (on my side at least)
But i found some other problems, which **are** solved also on this PR:
* Open a data, activate PolygonROI, draw a ROI, change the current toolbox -> the ROI and tick are not cleared
* Open a data, activate, split, change the current toolbox, go back to PolygonROI -> the toolbox is blocked on deactivate mode
* Open a data, activate, split, close the application -> crash
* Solve some typos and ergonomic position of some buttons to a better …
=> [PolygonROI] solve graphical/ergonomy pb and crashes (split, clear)

src/plugins/legacy/meshManipulation/meshManipulationToolBox.cpp
- Add a permanent item in the transformation list that references the current applied transformation: this makes it clearer for users when exporting transformations
- The names of imported transformation from layer data are suffixed with the series description
=> [Mesh manipulation] Clearer mesh manip3.2.x

src/layers/legacy/medCoreLegacy/database/medDataManager.cpp, src/layers/legacy/medCoreLegacy/database/medDataManager.h, src/layers/legacy/medCoreLegacy/database/medDatabaseExporter.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseExporter.h
- Fix problem when exporting very big medAbstractData onto disk: the object would be garbage collected before the writing would finish. Correct usage of smart pointers fixes this.
=> [medDatabaseExporter] Fix problem when exporting big data

src/layers/legacy/medCoreLegacy/medExternalResources.cpp, src/layers/legacy/medCoreLegacy/medExternalResources.h
(based on https://github.com/medInria/medInria-public/pull/863)
commit: https://github.com/medInria/medInria-public/commit/e173ea6550c7158f4eb3c0544f03c9071e992a41
Fixes a crash that occurs when retrieving more than one external resource for a single target.
=> [medExternalResources] bundle object should not be freed

src/layers/legacy/medCoreLegacy/medExternalResources.cpp, src/layers/legacy/medCoreLegacy/medExternalResources.h
The embedded Python will be stored in the medPython framework. For this to work I need to set the Python module search path to the medPython resource directory (future plugins that provide additional embedded modules will need to add their resource paths too)
=> [medExternalResources] allow retrieval of the resource directories

src/layers/legacy/medRegistration/itkProcessRegistration.h
A small change on the documentation of itkProcessRegistration: `channel` is not a parameter.
:m:
=> [itkProcessRegistration] doxygen param problem

src/cmake/module/add_external_resources.cmake
Following discussion with @Florent2305, we decided to make the following changes to the `add_external_resources` macro:
- Change the custom command that copies the files so that it executes at post build time.
- Remove the RCC option. It is not necessary and creates some complication with the other changes.
=> [add_external_resources] remove RCC option, use POST_BUILD

src/plugins/legacy/polygonRoi/repulsor/vtkInriaInteractorStylePolygonRepulsor.cxx, src/plugins/legacy/polygonRoi/repulsor/vtkInriaInteractorStylePolygonRepulsor.h
minor mem leak on  vtkInriaInteractorStylePolygonRepulsor
modernize with override and delete.
=> mem leak on  vtkInriaInteractorStylePolygonRepulsor (polygonRoi)

src/cmake/module/set_plugin_install_rules.cmake, src/layers/legacy/medCoreLegacy/medPluginManager.cpp, src/layers/legacy/medCoreLegacy/medPluginManager.h
I modified `set_plugin_install_rules` to allow using `add_external_resources` on plugins. When using this macro on macOS the library becomes a framework. This causes an issue when loading because QPluginLoader complains it can't find the shared library. To fix this we need to replace the framework path with the path to the library inside the framework (I don't know why QPluginLoader doesn't do this automatically).
=> Allow framework plugins and resources

src/layers/legacy/medCoreLegacy/gui/factories/medToolBoxFactory.cpp, src/layers/legacy/medCoreLegacy/gui/factories/medToolBoxFactory.h, src/layers/legacy/medCoreLegacy/gui/factories/medWorkspaceFactory.cpp, src/layers/legacy/medCoreLegacy/gui/factories/medWorkspaceFactory.h
The factory classes use functions pointers to create instances. SWIG cannot map Python functions to C function pointers, so it is not possible to register types from Python code the way it is done on the C++ side. As a workaround I created generic creator functions that take a pointer to a Python class and create an instance of that class. In order for that to work we need to add an (optional) argument to the creator functions.
(These changes should be extended to all the factories later on. I only did the ones needed for the pipeline plugin)
=> Optional argument to workspace and toolbox creator functions

src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.cpp, src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h, src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp, src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.h, src/layers/legacy/medCoreLegacy/database/medAbstractDbController.h, src/layers/legacy/medCoreLegacy/database/medDataManager.cpp, src/layers/legacy/medCoreLegacy/database/medDataManager.h, src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.h, src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentItem.h, src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentItem_p.h, src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.cpp, src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.h, src/layers/legacy/medCoreLegacy/database/medDatabaseRemover.cpp, src/plugins/legacy/polygonRoi/polygonLabel.cpp
Create a json file attached to a data produced in polygonROI toolbox
Here is a example
```
{
"incepto": {
"createdDate": "2021-09-14T10:10:05.263",
"id": "1.z.z.z.z.z.xxxxx.x.x.x.xxxx.xxxx.xxxxxxxxxxxxxxxxxx",
"modifiedDate": "2021-09-14T10:10:05.263",
"userId": "",
"value": {
"caracteristique": {
"pirads": "4",
"sequence": "T2",
"targetId": "2",
"zone": "ZT"
},
"mha_filename": "1.2.826.0.1.3680043.2.1143.5346340657416896685415421747836590732",
"reference": "Daicap_Prostate_Target_2_ZT_PIRADS4_Segmentation"
}
},
"originalMetaData": {
"patientId": "fooId",
"patientName": "fooName",
"seriesInstanceUID": "1.x.x.x.x.x.xxxxx.x.x.x.xxxx.xxxx.xxxxxxxxxxxxxxxxxx",
"studyDescription": "bar Description",
"studyInstanceUID": "1.y.y.y.y.y.yyyyy.x.x.x.xxxx.xxxx.xxxxxxxxxxxxxxxxxx"
}
}
```
- incepto : …
=> [NEW] [DAICAP] [INCEPTO] - Create an attached json file 

src/layers/legacy/medCoreLegacy/database/medAbstractDbController.h, src/layers/legacy/medCoreLegacy/database/medDataManager.cpp, src/layers/legacy/medCoreLegacy/database/medDataManager.h, src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseController.h, src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.h, src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseReader.h
_(edited after refactoring)_
This adds the possibility to get information on the type of a data in the database. This is done by adding a `medDataManager::getDataType` method that returns the `QMetaObject` instance of the data class. In order for this to work I have added an option in the DB loading mechanism that retrieves empty `medAbstractData` instances (the actual data is not loaded, only the `dtkAbstractDataReader::readInformation` method is used to obtain the instance.
=> add "shallow" loading option when retrieving data

src/app/medInria/resources/medInria.qss, src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h, src/layers/legacy/medCoreLegacy/views/medAbstractLayeredView.cpp, src/layers/medWidgets/process/arithmetic_operation/medAbstractArithmeticOperationProcessPresenter.cpp, src/layers/medWidgets/process/diffusion_processes/medAbstractDWIMaskingProcessPresenter.cpp, src/layers/medWidgets/process/diffusion_processes/medAbstractDiffusionModelEstimationProcessPresenter.cpp, src/layers/medWidgets/process/diffusion_processes/medAbstractDiffusionScalarMapsProcessPresenter.cpp, src/layers/medWidgets/process/diffusion_processes/medAbstractTractographyProcessPresenter.cpp, src/layers/medWidgets/process/diffusion_processes/medDiffusionModelEstimationMetaProcessPresenter.cpp, src/layers/medWidgets/process/mask_image/medAbstractMaskImageProcessPresenter.cpp, src/layers/medWidgets/process/morphomath_operation/medAbstractMorphomathOperationProcessPresenter.cpp, src/layers/medWidgets/process/single_filter/medAbstractSingleFilterOperationProcessPresenter.cpp, src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp, src/plugins/legacy/medRegistrationWorkspace/medRegistrationWorkspace.cpp, src/plugins/legacy/reformat/resliceToolBox.cpp
This PR:
* fix https://github.com/medInria/medInria-public/issues/633 where we were loosing the default background color/buttons after removing a data in a view in fix containers workspace (Filtering, Registration for instance).
* fix https://github.com/medInria/medInria-public/issues/912 where the Tools button were locked on an empty view in the same fix containers.
* fix the "Unable to retrieve data at layer: 0 from: \"medVtkView\"" warning after removing a data
PS: this PR has been made on master branch since medInria3.2 was temporary not compiling on my side due to a change in pre-requisites, but these fixes are really interesting for med3.2 aswell.
:m:
=> [viewContainer] background and buttons by default without data

src/plugins/legacy/reformat/resliceToolBox.cpp
A 1-line PR which:
* fix #920 
* fix #916
The removal of the data in the view did not reset the currentView variable.
PS: linked to https://github.com/medInria/medInria-public/pull/921
:m:
=> [Reslice] solve crashs after removing a data in view

src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp, src/plugins/legacy/voiCutter/voiCutterToolBox.cpp
Fix #919
This PR:
* Change the display of the output at the end of the process in `VarSegToolBox::displayOutput()`, which was crashing with a 3D/2D view
* Remove 2 non-used variable (mprOn was always set to false, and originalView not used if mprOn is set at false)
* The `d->currentView->property("Orientation")` line created a warning since there are no Orientation property here
* Handle `updateView` if the view is empty
* The explanation text is smaller because it created a small graphic bug with the information button
:m:
=> [VariationalSeg] solve crash avec 3D->2D view segmentation

src/plugins/legacy/itkDataSHImage/interactors/itkDataSHImageVtkViewInteractor.cpp, src/plugins/legacy/itkDataTensorImage/interactors/itkDataTensorImageVtkViewInteractor.cpp
From this old PR https://github.com/medInria/medInria-public/pull/684
Solves memory leaks in itkDataSHImageVtkViewInteractor and itkDataTensorImageVtkViewInteractor with solution by @Florent2305.
Compiled on Ubuntu 20.04, tested with classic data (3D volume), not tensors.
:m:
=> [itkDataSHImageVtkViewInteractor, itkDataTensorImageVtkViewInteractor] mem leak

src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
- open test_mesh.vtk go to attributes Zones -> min and max intensity are at 0 but they should not the true value is 1
[test_mesh.zip](https://github.com/medInria/medInria-public/files/6692796/test_mesh.zip)
=> [medDoubleParameterL]: fix wrong (0,0) shown values when attributes has only one value for all mesh

src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp
Fix #925
This avoids the output duplication after a manual registration.
:m:
=> [ManualRegistration] avoid duplication in outputs

src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp
`medStatusBar::removeMessage` assumes the message being removed is the first on the list. This is not always the case and causes a crash when it happens because the deleted message is still on the stack.
=> [medStatusBar] removal of wrong message

src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSet.cxx, src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSet.h, src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.cxx, src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.h, src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
- Attribute single step is now computed from the values of the array, not fixed to 0.1
- Fix memleaks by changing the GetScalarRange method: now the range array is passed as parameter
=> [Mesh attribute range] Compute single step, fix memleak.

src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.cpp, src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.h
Remove a warning in ClutEditor and a TODO comment in the code
`AutoMoc: /home/[...]/medInria-public/src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.h:76: Warning: Class medClutEditorVertex implements the interface QGraphicsItem but does not list it in Q_INTERFACES. qobject_cast to QGraphicsItem will not work!`
:m:
=> [ClutEditor] rm warning with QGraphicsItem and QObject

src/CMakeLists.txt, src/layers/medPython/cmake/embed_python.cmake
Making the python headers private sources of medPython solves the issue of the files not being found elsewhere (and as a consequence there is no need for the policy that required version 3.20)
=> [medPython] fix issue with python headers not found

src/layers/medPython/cmake/embed_python.cmake
install_name_tool is a mac command not present (or needed) on other other platforms.
=> Remove mac-specific command

src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.cxx, src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.h, src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx, src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.h, src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriter.cpp
- In volume meshes, edges, triangles, ridges are read and not only tetrahedra as before.
- Similarly in surface meshes, edges, ridges are read and not only triangles.
- Add vtu reader and writer for mesh of type unstructured grid
- Prevent use of vtp writer for unstructured grid and vtu writer for polydata
- Check the version of the vtk file to avoid crash due to the new format introduced in vtk 9
=> Fix mesh readers

superbuild/CMakeLists.txt, superbuild/projects_modules/DCMTK.cmake, superbuild/projects_modules/ITK.cmake, superbuild/projects_modules/QtDCM.cmake, superbuild/projects_modules/RPI.cmake, superbuild/projects_modules/TTK.cmake, superbuild/projects_modules/VTK.cmake, superbuild/projects_modules/dtk.cmake, superbuild/projects_modules/dtkImaging.cmake, superbuild/projects_modules/medInria.cmake
This PR fixes https://github.com/medInria/medInria-public/issues/439.
* CMAKE_BUILD_TYPE_medInria was never used, only medInria _BUILD_TYPE in medInria.cmake
* CMAKE_BUILD_TYPE_externals_projects was too long
:m:
=> [CMake] CMAKE_BUILD_TYPE(s) cleaning

src/app/medInria/main.cpp
Originally looked at in https://github.com/medInria/medInria-public/pull/643.
Update QSurfaceFormat to the parameters used by VTK in `QVTKRenderWindowAdapter::defaultFormat`.
Researches done with @Florent2305.
Tests done on Ubuntu 20.04.
:m:
=> [QSurfaceFormat] use VTK surface format parameters

src/layers/legacy/medCoreLegacy/medGlobalDefs.cpp
Based on the last part of this old pull request : https://github.com/medInria/medInria-public/pull/643
QGLWidget class is deprecated, and now replaced by QOffscreenSurface and QOpenGLContext.
:m:
=> [gpuModel] QGLWidget deprecated, change to QOffscreenSurface/QOpenGLContext

src/plugins/legacy/itkFilters/itkFiltersComponentSizeThresholdProcess.cpp, src/plugins/legacy/medMaskApplication/medMaskApplicationToolBox.cpp
fix https://github.com/medInria/medInria-public/issues/798
fix https://github.com/medInria/medInria-public/issues/588
From objectives 4.x https://github.com/medInria/medInria-public/issues/864
This PR:
* "Remove isolated voxels/pixels" is now working with masks with non 0/1 values
* "Mask Application" now updates the background value of the mask
:m:
=> [Filtering] background values for MaskAppli & ComponentSize

src/plugins/legacy/reformat/resliceToolBox.cpp
Fix a crash when you switch the Spacing/Dimension parameters. 
Appears after https://github.com/Inria-Asclepios/medInria-public/pull/718 because one of the updateView is empty at the end.
:m:
=> [Reslice] fix crash with spacing/dim parameters

src/layers/legacy/medCoreLegacy/gui/factories/medWorkspaceFactory.cpp
Since this commit https://github.com/medInria/medInria-public/commit/19da358e10bbc7a5c90358981b25bf2f8b61b56c there was an empty widget at the top left of the workspaces, which was hiding the top of the database column.
This PR hides it.
:m:
=> [GUI] empty widget was locked at top left of workspaces

src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp, src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.h, src/layers/legacy/medCoreLegacy/gui/toolboxes/medAbstractSelectableToolBox.cpp, src/layers/legacy/medCoreLegacy/gui/toolboxes/medAbstractSelectableToolBox.h, src/layers/legacy/medCoreLegacy/gui/toolboxes/medSelectorToolBox.cpp
The following changes came about from working on the pipelines:
- By default a toolbox's title is now equal to its name (before this it was empty if not set explicitly).
- The functions to add and remove toolboxes from a workspace are no longer slots.
- A selectable toolbox is no longer assumed to be part of a plugin.
=> Default toolbox title, non-plugin selectable toolbox, move some slots to normal functions

src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBox.cpp, src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBox.h, src/layers/medPython/cmake/generate_python_resources.cmake, src/layers/medPython/tools/CMakeLists.txt, src/layers/medPython/tools/bindings/medInria/data.i, src/layers/medPython/tools/bindings/qt/header.i
Aside from some minor python fixes, this PR adds a couple important functions in `medToolBox`. These are changes I made a while back to replace the hacks we made in the old pipeline code when accessing and modifying toolbox widgets (to set values, click buttons etc.). The following virtual functions are added:
- `getComponent`: used to click buttons for example
- `getValue` and `setValue`: used to access things like spinbox values.
The old pipeline code used `QObject::findChild` to achieve this, and the default implementation of these functions does the same. The old code also had parts that directly accessed some special functions in the histogram toolbox (which meant we had to link with that plugin). This is no longer possible because the pipeline code is in the core, so I have modified …
=> [medToolBox] component and value accessors

src/app/medInria/main.cpp, src/layers/medPython/base/core/medPythonCoreInit.cpp, src/layers/medPython/base/core/medPythonCoreInit.h, src/layers/medPython/base/medPython.h, src/layers/medPython/base/medPythonInit.cpp, src/layers/medPython/base/medPythonUtils.cpp, src/layers/medPython/base/medPythonUtils.h, src/layers/medPython/tools/medPythonSettingsWidget.cpp, src/layers/medPython/tools/medPythonSettingsWidget.h, src/layers/medPython/tools/medPythonTools.cpp
Adds a settings value that contains additional python paths to append to the python modules path at startup.
A python settings widget is also added to allow the user to add/remove paths.
=> [medPython] settings to allow adding python paths (for python plugins)

src/layers/medPython/tools/CMakeLists.txt, src/layers/medPython/tools/bindings/medInria/data.i, src/layers/medPython/tools/bindings/qt/hash.i, src/layers/medPython/tools/bindings/qt/header.i, src/layers/medPython/tools/bindings/qt/list.i
- adds bindings for QHash
- corrects bindings for `medAbstractData` smart pointers
- allows binding of output arguments
=> [medPythonTools] improve bindings and add QHash

src/layers/legacy/medUtilities/medUtilities.cpp, src/layers/legacy/medUtilities/medUtilities.h, src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp, src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
Based on PR:
* https://github.com/Inria-Asclepios/medInria-public/pull/647
* https://github.com/Inria-Asclepios/medInria-public/pull/730
Twin PR on https://github.com/medInria/medInria-public/pull/971
Compute the right cursor size in the Paint tool, taking into account some screens (for instance Retina) which have different pixel ratio.
:m:
=> [Paint] device ratio for cursor size --master

src/layers/legacy/medUtilities/medUtilities.cpp, src/layers/legacy/medUtilities/medUtilities.h, src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp, src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
Based on PR:
* https://github.com/Inria-Asclepios/medInria-public/pull/647
* https://github.com/Inria-Asclepios/medInria-public/pull/730
Compute the right cursor size in the Paint tool, taking into account some screens (for instance Retina) which have different pixel ratio.
:m:
=> [Paint] device ratio for cursor size

src/layers/medPython/base/error/medPythonBaseException.cpp
The `qUtf8Printable` macro is the recommended way to convert a `QString` to a UTF8-encoded `const char` pointer (it is equivalent to calling `str.toUtf8().constData()`). The problem is the `toUtf8()` call creates a temporary `QByteArray`, and therefore the macro is not suitable for return values (as is done in `medPythonBaseException::what()`) because the pointer will not be valid after. To fix this problem we store the `QByteArray` in the exception instance instead of the initial `QString`.
=> [medPythonBaseException] fix exception message bug

src/layers/medPython/base/CMakeLists.txt, src/layers/medPython/base/core/medPythonCoreInit.cpp, src/layers/medPython/base/medPythonUtils.cpp, src/layers/medPython/base/medPythonUtils.h, src/layers/medPython/tools/CMakeLists.txt, src/layers/medPython/tools/medPythonTools.cpp, src/layers/medPython/tools/medPythonTools.h, src/layers/medPython/tools/python/__init__.py, src/layers/medPython/tools/python/console.py
This PR introduces the following changes:
- Add try-catch blocks to handle any Python-related exceptions that might occur during initialisation of medPython.
- Improve documentation, in particular to warn which externally accessible medPython functions can throw exceptions.
- At startup, loop over all the top-level packages found in the Python paths and loads the ones with the prefix `medInria_` in their name (this is how other Python libraries such as Flask load their plugins.
- In the medInria module, add two dicts `loaded_plugins` and `failed_plugins` and a function `plugins()` to get information on the loaded plugins (and any errors).
- Add a message in the console to warn of failed plugins.
- Add a C++ function to allow printing text to the Python console.
- Some changes in how the …
=> [medPython] handle errors during init and plugin loading

src/layers/medPython/base/conversion/medPythonQObjectConversion.cpp, src/layers/medPython/base/objects/medPythonAbstractObject.cpp, src/layers/medPython/base/objects/medPythonAbstractObject.h, src/layers/medPython/cmake/add_python_bindings.cmake, src/layers/medPython/tools/bindings/medInria/data.i, src/layers/medPython/tools/bindings/medInria/gui.i, src/layers/medPython/tools/bindings/medInria/header.i
Changes:
- Add `isInstance` and `isSubType` methods to the Python object API. This is especially useful for SWIG director classes (which allows C++ classes to be extended in Python).
- Generalise director classes instead of explicitly specifying which classes need them.
- Fix some minor bugs.
=> [medPython] isInstance, isSubType, directors

src/layers/legacy/medCoreLegacy/gui/toolboxes/medSelectorToolBox.cpp
Clicking on the medSelectorToolBox combobox and choosing the same current toolbox was running the `clear()` method of toolboxes. This PR avoids that.
:m:
=> [medSelectorTlbx]choose the current tlbx in selector do not run clear()

packaging/apple/ApplePackaging.cmake, packaging/apple/mac_packager.sh.in
The dtkDeploy tool does not update the install names of the plugin dylibs:
These should be set to `@executable_path/../PlugIns/[library name]`.
(this bug has no impact on the execution of the current application but causes a crash in an upcoming PR for Python)
=> mac_packager: fix plugin install names

packaging/apple/ApplePackaging.cmake, packaging/apple/mac_packager.sh.in, src/cmake/module/set_lib_install_rules.cmake, src/layers/legacy/medCoreLegacy/CMakeLists.txt, src/layers/legacy/medImageIO/CMakeLists.txt, src/layers/legacy/medLog/CMakeLists.txt, src/layers/legacy/medPacs/CMakeLists.txt, src/layers/legacy/medRegistration/CMakeLists.txt, src/layers/legacy/medUtilities/CMakeLists.txt, src/layers/legacy/medVtkDataMeshBase/CMakeLists.txt, src/layers/legacy/medVtkInria/CMakeLists.txt, src/layers/medComposer/CMakeLists.txt, src/layers/medCore/CMakeLists.txt, src/layers/medPython/base/CMakeLists.txt, src/layers/medPython/tools/CMakeLists.txt, src/layers/medWidgets/CMakeLists.txt
(based on https://github.com/medInria/medInria-public/pull/993)
(commit (https://github.com/medInria/medInria-public/commit/51a7f1d918396abb65a8708d54c697d14d566583)]
Adds the concept of resource libraries which are libraries that must be packaged with the application but are not dependencies of the executable. The Python binding system creates shared libraries that are loaded by Python when the corresponding module is loaded. These libraries are not linked into the executable and therefore do not appear as dependencies. This causes a problem on macOS with dtkDeploy because it uses otool to find which libraries should be copied to the bundle. Plugins are handled differently: dtkDeploy imports all the plugins found in the designated directories. We can therefore use this to allow dtkDeploy …
=> Resource libraries

src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp, src/layers/legacy/medImageIO/itkDCMTKImageIO.h
The method that gets the position of a slice on the stacking axis was z-specific and only worked on axial acquisition. This method was involved in both the determination of the origin of the image and the ordering of slices in the buffer.
Furthermore, the aforementioned slice ordering code is redundant with the code above it, which led to a double order inversion instead of a simple inversion of the order in which slices are stacked in the buffer, causing the images to be mirrored in case the stacking direction is the opposite of the acquisition direction.
**Before changes:**
Here on a coronal acquisition, the patient is facing the wrong way on y
Here on a sagittal acquisition, the hemispheres are mirrored, which is confirmed by opening the same data on other readers such as 3D Slicer …
=> Fixing mirrored DICOM images and their origin

src/app/medInria/areas/browser/medBrowserArea.cpp, src/layers/legacy/medCoreLegacy/gui/medToolBoxContainer.cpp
This Pull Request solves 2 problems:
* there were ghost toolboxes in tabs in Browser area (fix https://github.com/medInria/medInria-public/issues/949) -> no more ghosts
* the default tab was defined before adding the data sources, which was not working, and users are often lost with Browser -> File system is the default one
:m:
=> [Browser] ghost toolboxes from PACS/CD tab in DB and FS tabs

src/app/medInria/medSaveModifiedDialog.cpp
Since this dialog has both a button "Save and quit" and "Quit without saving", the user expects to not quit without saving if they click on "Save and quit". This was reported after cases of data loss.
The suggested fix changes the default values of the checkboxes in the unsaved data list to checked.
=> Check datasets by default in save-before-quitting dialog

src/layers/medCore/dataSource/medDataModel.cpp, src/layers/medCore/dataSource/medSourceItemModel.cpp, src/layers/medWidgets/dataSource/medSourceItemModelPresenter.cpp, src/plugins/legacy/medAPHPDataSource/medAPHP.cpp, src/plugins/legacy/medAPHPDataSource/medAPHP.h, src/plugins/legacy/medSQLite/medSQLite.h, src/plugins/legacy/medSQLite/medSQLite.txx
1. Dev Filters in Legacy SQLite DB source (from APHP model) to enhance debugging of filters
2. Fix crash when a filtering is applied in browser while data is already in view (want to keep it)
[WARNING] - We are not totally sure that the bug is totally fixed. The code is more robust.
=> Patient filter sq lite db

src/plugins/legacy/medVtkView/medVtkView.cpp
Calling mapWorldToDisplayCoordinates from medVtkView class leads to a crash. This is due to the fact that currentview is always null. To fix it we use imageView2D as done for mapDisplayToWorldCoordinates function
=> Fix mapWorldToDisplayCoordinates function 

src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp, src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp, src/layers/legacy/medCoreLegacy/database/medLocalDbController.cpp, src/layers/legacy/medCoreLegacy/database/medLocalDbController.h, src/layers/legacy/medCoreLegacy/gui/database/medDatabaseMetadataItemDialog.cpp, src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp, src/layers/legacy/medImageIO/itkDCMTKImageIO.h, src/layers/legacy/medUtilities/medUtilities.cpp, src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp, src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
-When writing a dicom file study date, study time, series times and series dates are needed if they are not provided by the data the writer uses the current time but the fractional part of a second could change between slices which can be problematic for some software like lead-DBS used by RebrAIn. Indeed for lead-DBS slices are not stacked if these values change.
-the kvp metadata information was not kept inside the database so the dicom writer was adding 1 by default to all ct dicom 
-Morever we now read patient age from the database so this information is accessible from the medinria metadata list interface
=> Insert some useful metadatas into the database

src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
Same as https://github.com/Inria-Asclepios/medInria-public/pull/736
Since this PR https://github.com/medInria/medInria-public/pull/902 some attributes of meshes were not displayed in color in 3D orientation. It was because vtkIdFilter vas not properly initialized. This PR solves this problem.
:m:
=> [Attributes] some mesh fields not displayed in color in 3D

src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h
From https://github.com/Inria-Asclepios/medInria-public/pull/740
These changes allow to reset the central inner widget of a view when it was changed by a toolbox. Before that, in some toolboxes, we had graphic bugs in the central widget after a reset.
:m:
=> [medViewContainer] allow to reset central view widgets --merge3.2

src/cmake/module/set_lib_install_rules.cmake
Fix issues of type medCoreLegacy_LIBRARY-NOTFOUND when compiling with external plugins
=> [Install rules]: fix link problems between medInria and external plugins

src/app/medInria/medMainWindow.cpp, src/layers/legacy/medImageIO/itkDataImageReaderBase.cpp, src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp, src/plugins/legacy/itkDataImage/readers/itkGDCMDataImageReader.cpp, src/plugins/legacy/itkDataSHImage/readers/itkDataSHImageReader.cpp, src/plugins/legacy/itkDataSHImage/writers/itkDataSHImageWriterBase.cpp, src/plugins/legacy/itkDataTensorImage/readers/itkDataTensorImageReaderBase.cpp, src/plugins/legacy/itkDataTensorImage/writers/itkDataTensorImageWriterBase.cpp, src/plugins/legacy/medVtkFibersData/readers/medVtkFibersDataReader.cpp, src/plugins/legacy/medVtkFibersData/writers/medVtkFibersDataWriter.cpp, src/plugins/legacy/vtkDataMesh/readers/vtkDataMesh4DReader.cpp, src/plugins/legacy/vtkDataMesh/writers/vtkDataMesh4DWriter.cpp
Fix https://github.com/medInria/medInria-public/issues/1027
Solve import error when there are accents in a data path to import.
:m:
=> [Path] switch to utf8 to accept accented paths

superbuild/patches/VTK.patch
On Fedora 33 with gcc10 (we are at gcc9 on Ubuntu 20 for instance), the gcc version number is not found... because it has two digits. This is because we are on VTK 8.1.2 which is a bit old. This will be solved in new versions.
:m:
=> [VTK] patch to compile with GCC 10 - fedora

src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.cpp, src/plugins/legacy/meshMapping/meshMappingToolBox.cpp
Solve toolbox width error in case of opening data with long data array name, before opening the toolbox.
:m:
=> [Combobox] right size with long data array name

packaging/apple/mac_packager.sh.in
We have an error in packaging of medInria/MSC:
```
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't open file: /System/Volumes/Data/builds/workspace/music-macos-free/build/medInria-build/bin/TmpInstall/medInria.app/Contents/PlugIns/*.dylib (No such file or directory)
mv: rename /System/Volumes/Data/builds/workspace/music-macos-free/build/medInria-build/bin/TmpInstall/medInria.app/Contents/PlugIns/*.dylib to /System/Volumes/Data/builds/workspace/music-macos-free/build/medInria-build/bin/TmpInstall/medInria.app/Contents/Frameworks/*.dylib: No such file or directory
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't open file: /System/Volumes/Data/builds/workspace/music-macos-free/build/medInria-build/bin/TmpInstall/medInria.app/Contents/Fra …
```
=> [Package] rm TmpInstall macOS code which does not package

RELEASE_NOTES.txt, src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp, src/plugins/legacy/variationalSegmentation/vtkLandmarkSegmentationController.cpp
This PR:
* fix https://github.com/medInria/medInria-public/issues/793 removing the white plans on output mask
* enhance the GUI, the first button is the saving of the mask, before the application of the mask on the view, and exported data name shorten
* the application of the mask save the applied data, not the mask, which is done with the mask button
:m:
=> [Variational] GUI, applied data saved, data name, spacing error

CONTRIBUTING.md
Clarify the following point :
- A 'master' branch exists for each major version of medInria still under development.
- The master branch of latest version of medInria is named *master*
- 'Masters' branches of previous major version of medInria are named with the pattern `medInriaX.Y.x`
=> Update contributing rules in CONTRIBUTING.md

src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
Same as https://github.com/medInria/medInria-public/pull/1051 on master branch.
> On virtual machine using mesa/x.org drivers each time a thumbnail was generated an orphaned widget was seen on the screen.
> To fix this issue the driver is added to the list of drivers capable of on offscreen rendering in generateThumbnailInGuiThread method.
=> [medAbstractData]: add drivers capable of on offscreen rendering in generateThumbnailInGuiThread - master

src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
On virtual machine using mesa/x.org drivers each time a thumbnail was generated an orphaned widget was seen on the screen.
To fix this issue the driver is added to the list of drivers capable of on offscreen rendering in generateThumbnailInGuiThread method.
=> [medAbstractData]: add drivers capable of on offscreen rendering

src/CMakeLists.txt, superbuild/CMakeLists.txt, superbuild/projects_modules/PYNCPP.cmake, superbuild/projects_modules/medInria.cmake
The PYNCPP project compiles it's own version of Python (or installs one on Windows), with ._pth configuration file support on all platforms, and provides an API to embed Python in a CPP application.
(This only adds the external project. The runtime initialisation of Python and the packaging aspects are not handled here)
=> Add PYNCPP external project

src/layers/legacy/medCoreLegacy/parameters/medViewParameterGroupL.cpp
Same as https://github.com/medInria/medInria-public/pull/1060
Fix https://github.com/medInria/medInria-public/issues/995
The views are already cleaned at closing through a signal set in `medViewParameterGroupL::addImpactedView`. 
Removing them manually in `~medViewParameterGroupL` leads to trying to remove already removed views, generating a crash.
:m:
=> [Four-views] solve crash closing the views --3.3

src/layers/legacy/medCoreLegacy/parameters/medViewParameterGroupL.cpp
Fix https://github.com/medInria/medInria-public/issues/995
The views are already cleaned at closing through a signal set in `medViewParameterGroupL::addImpactedView`. 
Removing them manually in `~medViewParameterGroupL` leads to trying to remove already removed views, generating a crash.
:m:
=> [Four-views] solve crash closing the views

src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.h
Fix https://github.com/medInria/medInria-public/issues/491
It was a very old bug in medInria from 3.0. The zoom was incorrectly set at opening of data, specially some data as the medInria data test "CT_mouse.mha". 
In this PR, the zoom value is calculated through only x and y values, not z. 
Let me know if you think this new behavior could create any problem elsewhere.
:m:
=> [Zoom] proper zoom displaying data on xy and not xyz

src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.cpp, src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.h
Fix https://github.com/medInria/medInria-public/issues/517
Fix https://github.com/medInria/medInria-public/issues/1066
There were problems with the tabs in medInria, leading to users not using them (and they have been locked in most of the workspaces). If you want to test, check the Visualization workspace.
This PR adds handling of tabs when they are switched, or removed.
:m:
=> [Tabs] handling of tabs: removal, switch

src/plugins/legacy/reformat/medResliceViewer.cpp, src/plugins/legacy/reformat/medResliceViewer.h, src/plugins/legacy/reformat/resliceToolBox.cpp
Fix https://github.com/medInria/medInria-public/issues/674
When the user uses the dimension or spacing tool, there is no more a graphic zoom bug on the views.
To find the solution, i needed to clean the code (specially askedSpacingOrSizeChange) to create a clear separation between spacing change and size (previously 'dimension') change, because a lot of the widgets have been wrongly name only with Spacing, instead of both. This is surely due to code history, spacing was coded before.
:m:
=> [Reslice] fix zoom error + code clarity

src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
Same as https://github.com/medInria/medInria-public/pull/1073
Fix https://github.com/medInria/medInria-public/issues/726
Create the mask data in Paint when the user clicks on "Paint/Erase", not at the first click on the image. The creation of the mask is too slow, and the drawing not smooth at the beginning.
Also, switching from Magic Wand to Paint/Erase was not hiding the removeSeed button.
:m:
=> [Paint] create mask before trying to paint + hide a button

CMakeLists.txt, src/CMakeLists.txt
The minimum required cmake version is still set at 3.3 on medInria 3. This means that for any cmake policy introduced after 3.3 the default behaviour of the policy will be chosen unless it is manually set. This is causing issues with the python embedding code.
=> Set cmake minimum version to 19 for medInria project

src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp, src/layers/legacy/medImageIO/itkDCMTKImageIO.h
Exporting and importing DICOM from medInria3.4 i found a bug with some of my files with these kinds of error messages "DEBUG - ven. déc. 16 14:39:11 2022 - "itk::ERROR: DCMTKImageIO(0x7fcd340207f0): Ambiguous slice stack direction: -0.663234 0.582022 0.470501""
After some researches, it is linked to https://github.com/medInria/medInria-public/pull/1003
The solution is to continue the `GetPositionOnStackingAxisForImage` method, even if the axis is not what we may ask.
:m:
=> [DCM] do not corrupt exported/imported dcm with odd axis

src/app/medInria/areas/browser/medBrowserArea.cpp
Same as https://github.com/medInria/medInria-public/pull/987
This Pull Request solves 2 problems:
* there were ghost toolboxes in tabs in Browser area (fix https://github.com/medInria/medInria-public/issues/949) -> no more ghosts
* the default tab was defined before adding the data sources, which was not working, and users are often lost with Browser -> File system is the default one
:m:
=> [Browser] ghost toolboxes from PACS/CD tab in DB and FS tabs-master

src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
Same as this PR https://github.com/medInria/medInria-public/pull/886
If a mesh has an attribute with only one value (for instance 42), it was show as if the value was 0 (or one of the value already updated from an attribute with multiple values), and was not updated.
:m:
=> [medDoubleParameterL] fix wrong 0/0 values if attribute has only 1 value in a mesh

src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h, src/plugins/legacy/medVtkFibersData/manager/vtkFibersManager.cxx, src/plugins/legacy/vtkDataMesh/datas/vtkDataMesh4D.cpp, src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
Fusion of https://github.com/medInria/medInria-public/pull/902 and https://github.com/medInria/medInria-public/pull/1006 to enhance the way mesh are displayed/handled in 3D views. 
Use vtkGeometryFilter instead of vtkDataSetSurfaceFilter when adding a mesh in a view, and add vtkIdFilter for retrieval of original ids.
:m:
=> [Mesh Visu] improvements, use vtkIdFilter and vtkGeometryFilter

src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h, src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp, src/plugins/legacy/medRegistrationWorkspace/medRegistrationWorkspace.cpp
Apply https://github.com/medInria/medInria-public/pull/1012 which allow to recreate the central widget of a view (text + data open buttons). For instance in a toolbox if the inner widget of a toolbox has been changed, and we switch to an other toolbox.
On previous work https://github.com/medInria/medInria-public/pull/917 on master branch to solve some reinitialisation bugs of views with changed central widget (Filtering/Registration workspaces for instance).
OUTPUT view in Filtering, and FUSE view in Registration do not allow data drop, so i removed the opening buttons. OUTPUT view in Filtering in centered.
:m:
=> [CentralWidget] merge recreate default widget, and switch after data removal

RELEASE_NOTES.txt, src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp, src/plugins/legacy/variationalSegmentation/vtkLandmarkSegmentationController.cpp
Same as https://github.com/medInria/medInria-public/pull/1041
> This PR:
>  * fix https://github.com/medInria/medInria-public/issues/793 removing the white plans on output mask
>  * enhance the GUI, the first button is the saving of the mask, before the application of the mask on the view, and exported data name shorten
>  * the application of the mask save the applied data, not the mask, which is done with the mask button
:m:
=> [Variational] GUI, applied data saved, data name, spacing error -- master

src/layers/legacy/medCoreLegacy/parameters/medViewParameterGroupL.cpp
Same as https://github.com/medInria/medInria-public/pull/1060
Fix https://github.com/medInria/medInria-public/issues/995
The views are already cleaned at closing through a signal set in `medViewParameterGroupL::addImpactedView`. 
Removing them manually in `~medViewParameterGroupL` leads to trying to remove already removed views, generating a crash.
:m:
=> [Four-views] solve crash closing the views --master

src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.h
Same as https://github.com/medInria/medInria-public/pull/1064 on master.
It was a very old bug in medInria from 3.0. The zoom was incorrectly set at opening of data, specially some data as the medInria data test "CT_mouse.mha".  In this PR, the zoom value is calculated through only x and y values, not z.
:m:
=> [Zoom] proper zoom displaying data on xy and not xyz --master

src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.cpp, src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.h
Same as https://github.com/medInria/medInria-public/pull/1067 on master branch
Fix https://github.com/medInria/medInria-public/issues/517
Fix https://github.com/medInria/medInria-public/issues/1066
There were problems with the tabs in medInria, leading to users not using them (and they have been locked in most of the workspaces). If you want to test, check the Visualization workspace.
This PR adds handling of tabs when they are switched, or removed.
:m:
=> [Tabs] handling of tabs: removal, switch --master

src/plugins/legacy/reformat/medResliceViewer.cpp, src/plugins/legacy/reformat/medResliceViewer.h, src/plugins/legacy/reformat/resliceToolBox.cpp
Same as https://github.com/medInria/medInria-public/pull/1071
Fix https://github.com/medInria/medInria-public/issues/674
When the user uses the dimension or spacing tool, there is no more a graphic zoom bug on the views.
To find the solution, i needed to clean the code (specially askedSpacingOrSizeChange) to create a clear separation between spacing change and size (previously 'dimension') change, because a lot of the widgets have been wrongly name only with Spacing, instead of both. This is surely due to code history, spacing was coded before.
:m:
=> [Reslice] fix zoom error + code clarity --master

src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp, src/layers/legacy/medImageIO/itkDCMTKImageIO.h
From PRs https://github.com/medInria/medInria-public/pull/1003 and https://github.com/medInria/medInria-public/pull/1083
> The method that gets the position of a slice on the stacking axis was z-specific and only worked on axial acquisition. This method was involved in both the determination of the origin of the image and the ordering of slices in the buffer.
> 
> Furthermore, the aforementioned slice ordering code is redundant with the code above it, which led to a double order inversion instead of a simple inversion of the order in which slices are stacked in the buffer, causing the images to be mirrored in case the stacking direction is the opposite of the acquisition direction.
:m:
=> [Dicom] Fixing mirrored DICOM images and their origin

src/app/medInria/areas/homepage/medHomepageArea.cpp, src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.cpp, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp, src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp, src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp, src/plugins/legacy/itkFilters/itkMorphologicalFiltersToolBox.cpp, src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp, src/plugins/legacy/medBinaryOperation/medBinaryOperationToolBox.cpp, src/plugins/legacy/medMaskApplication/medMaskApplicationToolBox.cpp, src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionToolBox.cpp, src/plugins/legacy/medRemeshing/medRemeshingToolBox.cpp, src/plugins/legacy/medVtkFibersData/interactors/medVtkFibersDataInteractor.cpp, src/plugins/legacy/meshMapping/meshMappingToolBox.cpp, src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp, src/plugins/process/bias_correction/medItkBiasCorrectionProcess.cpp
Standardize the way tooltips are written:
* remove "\n" followed by space 
* remove dot at the end
* add line break for some long tooltips
:m:
=> [Tooltip] remove useless space, standardize format

src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.cpp, src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.cpp, src/plugins/legacy/iterativeClosestPoint/medICPFilter.cxx, src/plugins/legacy/iterativeClosestPoint/medICPFilter.h, src/plugins/legacy/meshMapping/meshMappingToolBox.cpp
Same as https://github.com/medInria/medInria-public/pull/1030 for medInria4
> To add fiducial registration error to ICP algorithm, it was necessary to recode the method.
> The toolbox was reorganized to have a more relevant disposition for the input parameters.
> The input parameters will be write in the transformation matrix file.
> The fiducial registration error is written in transformation matrix file and in the toolbox after process.
:m:
=> [iterativeClosestPoint] rewrite ICP code, reorganize toolbox, add fiducial registration error --master

src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.cxx, src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.h, src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx, src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.h, src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriter.cpp
Adapt this PR https://github.com/medInria/medInria-public/pull/954 to master branch.
> - In volume meshes, edges, triangles, ridges are read and not only tetrahedra as before.
> - Similarly in surface meshes, edges, ridges are read and not only triangles.
> - Add vtu reader and writer for mesh of type unstructured grid
> - Prevent use of vtp writer for unstructured grid and vtu writer for polydata
> - Check the version of the vtk file to avoid crash due to the new format introduced in vtk 9
=> [Meshes] Fix mesh readers -- master

src/layers/legacy/medCoreLegacy/database/medDataManager.cpp
When a user wants to export a data (right click -> Export, in database), the itk and vtk data are set as high priority, but the remaining of the list is random. This is a GUI problem for user, because it takes time to find the correct writer in the list if it's random.
This PR adds a `sort` method to the list of writers, before the high priority set to ITK and VTK writers.
:m:
=> [Writer] list in ascended order + priorities

src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp, src/layers/legacy/medImageIO/itkDCMTKImageIO.h
Same as https://github.com/medInria/medInria-public/pull/1083 on master branch.
Exporting and importing DICOM from medInria3.4 i found a bug with some of my files with these kinds of error messages "DEBUG - ven. déc. 16 14:39:11 2022 - "itk::ERROR: DCMTKImageIO(0x7fcd340207f0): Ambiguous slice stack direction: -0.663234 0.582022 0.470501""
After some researches, it is linked to https://github.com/medInria/medInria-public/pull/1003
The solution is to continue the `GetPositionOnStackingAxisForImage` method, even if the axis is not what we may ask.
:m:
=> [DCM] no corrupt exported/imported dcm with odd axis --master

src/app/medPluginGenerator/template/cmake, src/app/medPluginGenerator/template/filtering/cmake, src/app/medPluginGenerator/template/registration/cmake, src/plugins/legacy/itkINRDataImageReader/CMakeLists.txt, src/plugins/legacy/itkINRDataImageWriter/CMakeLists.txt, src/plugins/legacy/medCompositeDataSets/CMakeLists.txt, src/plugins/legacy/undoRedoRegistration/CMakeLists.txt
In order to easily maintain the cmake minimal versions, only the superbuild CMake and the src one set the minimal version (3.19 for now).
:m:
=> [CMake] minimum version at 3.19

src/app/medInria/areas/homepage/medHomepageArea.cpp, src/app/medInria/areas/homepage/medHomepageArea.h
On macOS the application menubar becomes a native menu bar in top of the screen (this could be deactivated by `menuBar()->setNativeMenuBar(false);`, but it's maybe better to use the native system). However, the cornerwidget or icons on menu bars were not working.
This PR switches the fullscreen icon to an Action->Fullscreen menu on macOS native menubar.
:m:
=> [macOS] corner widget in menubar was not visible

packaging/unix/Launchers.cmake
On Unix (Fedora - Ubuntu - macOS), a path in the launcher was not needed and created log error on Fedora and Ubuntu.
:m:
=> [Launcher] unix - not needed path

superbuild/external_projects_tools/EP_GithubSshTest.cmake
Github [changed their SSH RSA key](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/). And i saw that there was a github ssh test in medInria that could be updated, as done in this PR.
On some systems the Github solution to update the github key on our computers could not work (specially because of old versions of openssh), you could have a bug compiling medInria, locally or on Jenkins:
```bash
Cloning into 'VTK'...
Warning: the RSA host key for 'github.com' differs from the key for the IP address '[IP_ADRESS]'
Offending key for IP in /builds/.ssh/known_hosts:3
Matching host key in /builds/.ssh/known_hosts:12
Are you sure you want to continue connecting (yes/no)?
```
Solution : https://stackoverflow.com/questions/75830783/warning-remote-host-identification-has-changed-did-git …
=> [Github] ssh key change - update and information

superbuild/external_projects_tools/EP_GithubSshTest.cmake
Same as https://github.com/medInria/medInria-public/pull/1114
> Github [changed their SSH RSA key](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/). And i saw that there was a github ssh test in medInria that could be updated, as done in this PR.
:m:
=> [Github] ssh key change

src/layers/medCore/source/medDataHub.cpp, src/layers/medCore/source/medDataHub.h, src/layers/medCore/source/operating/medSourceHandler.cpp, src/layers/medCore/source/operating/medSourceHandler.h, src/layers/medCore/source/operating/medSourceModel.cpp, src/layers/medCore/source/operating/medSourceModel.h, src/layers/medCore/source/operating/medSourceModelItem.cpp, src/layers/medCore/source/operating/medSourceModelItem.h, src/layers/medWidgets/source/widgets/medDataInfoWidget.cpp, src/layers/medWidgets/source/widgets/medDataInfoWidget.h, src/layers/medWidgets/source/widgets/medSourcesWidget.cpp
This struct was declared differently in several files. Only the declaration in medSourceHandler for use in core and the declaration in medAbstractSource are kept.
Removed old implementations of get/set optionalAttributes and developed a new one. These methods are used to
- retrieve optional metadata from the source and store it in the model
- Display optional attributes in graphical elements
=> Clean declaration and usage of the dataSetAttributes structure:

src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
Opening a VTK from VTK 9 for instance in medInria 3.4 crashs the application. 
This PR avoids the crash.
:m:
=> [VTK] avoid med crash with wrong version of vtk files

src/app/medInria/areas/homepage/medHomepageArea.cpp
On Homepage, if the columns widgets are not displayed, we need to delete them to avoid memory leaks.
:m:
=> [MemoryLeak] homepage widgets

src/app/medInria/medLogger.cpp
Based on https://github.com/medInria/medInria-public/pull/1116
Commits: 
* https://github.com/medInria/medInria-public/commit/3a76bbf219d1ce65c829e024a934439f160e458d
* https://github.com/medInria/medInria-public/pull/1117/commits/b7431d770379fe9bb0474d26f5ffa8a0eda239dc
Solves several memory leaks in medLogger from teestreams, teedevices and d.
:m:
=> [MemoryLeak] medLogger TeeStreams, TeeDevices and d

src/app/medInria/main.cpp, src/app/medInria/medSplashScreen.cpp, src/app/medInria/medSplashScreen.h
This PR speeds up the launch of the software removing the display of each plugin name on it. 
On my machine (ubuntu) i had a 2 sec long splash screen, and with this i've got a instant launch. On some other machines, the splash screen is way longer so it can help too.
:m:
=> [SplashScreen] speeds up launch removing txt on splashscreen

src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp, src/layers/legacy/medCoreLegacy/parameters/medParameterPoolManagerL.cpp, src/layers/legacy/medCoreLegacy/parameters/medParameterPoolManagerL.h, src/layers/legacy/medCoreLegacy/parameters/medTimeLineParameterL.cpp, src/plugins/legacy/medVtkView/medVtkView.cpp
Fix a memory leak building the thumbnail importing a data. This PR removes the need to resize a pop-up to get a thumbnail with the right size. Instead, we resize a QImage.
Tested on Ubuntu and macOS.
-> memory leak fixed, no more po-up importing a data, and a quicker import.
:m:
=> [MemoryLeak] medVtkView::buildThumbnail

src/layers/legacy/medVtkInria/vtkImageView/vtkImage2DDisplay.cpp, src/layers/legacy/medVtkInria/vtkImageView/vtkImage3DDisplay.cpp
At compilation of medInria i had some warning as:
``` 
medInria-public/src/layers/legacy/medVtkInria/vtkImageView/vtkImage2DDisplay.cpp:67:60: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct medVtkImageInfo’; use assignment or value-initialization instead [-Wclass-memaccess]
67 |         memset(&m_sVtkImageInfo, 0, sizeof(m_sVtkImageInfo));
```
m_sVtkImageInfo is a complex structure with constructor and destructor, and should not be reset with memset.
:m:
=> [medVtkImageInfo] proper reset of a complex structure

src/layers/legacy/medVtkInria/vtkImageView/vtkImage2DDisplay.cpp, src/layers/legacy/medVtkInria/vtkImageView/vtkImage3DDisplay.cpp
An other way to be GCC compliant with m_sVtkImageInfo, seen with @Florent2305.
(previously changed on https://github.com/medInria/medInria-public/pull/1151)
:m:
=> [vtkImageInfo] an other way to reset the complex structure and please GCC

src/plugins/legacy/reformat/medCropToolBox.cpp
Minor issue found while reviewing a PR. An internal function using error codes returned `0` (i.e. success) instead of a failure code.
(the error case is never encountered but this is still a technical bug)
=> [medCropToolBox] fix error return value

src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.cpp, src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.h
From PR https://github.com/Inria-Asclepios/medInria-public/pull/805
> To avoid:
>  * a warning on Ubuntu because of the lack of `Q_INTERFACES(QGraphicsItem)`
>  * a compilation error on macOS because of its existence.
>  
> And to remove an old special comment ( 👀 ).
>  
> This PR changes the double inheritance in some histogram classes to a single one directly derived from QObjects.
:m:
=> [Histogram] switch QObject+QGraphicsItem to QGraphicsObject

src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
Since a thumbnail setting has been added to allow or not the creation of the thumbnail at data import, there is no need to display a warning about the existence of thumbnail during the saving of a temporary data.
:m:
=> [Thumbnail] no need to warn if no thumbn since the thumbnail setting added

src/layers/medCore/legacy/gui/lookUpTables/medClutEditor.h
The changes done in https://github.com/medInria/medInria-public/pull/1178 were already applied on medInria4/dev, however, this `todo` comment is useless now.
:m:
=> [medClutEditor] remove todo comments not needed anymore

src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp, src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.h
From PR https://github.com/Inria-Asclepios/medInria-public/pull/770
> This PR solves problems using tools in Paint:
> 
>  * Paint/Erase and Magic Wand buttons do not set properly their widgets.
>  * Clear button was hiding buttons even if data were in the view, run twice a part of the cleaning process, then and Add and Erase buttons when shown were not handled well.
:m:
=> [Paint] solve problems switching between tools (#770)

src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
From PR https://github.com/Inria-Asclepios/medInria-public/pull/767
> This PR allows to hide the Save button from outside, for instance from a pipeline.
:m:
=> [Paint] allow to forceHide the Save button (#767)

src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp, src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.cpp, src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.h, src/plugins/legacy/polygonRoi/viewinteractors/polygonRoi.cpp
From PR of MUSICardio https://github.com/Inria-Asclepios/medInria-public/pull/807
> There are some problems with Polygon ROI toolbox.
> 
> ### Solved in this PR
>  * If you want to draw a ROI with SHIFT-click, the first click was not drawing anything. This is important because some users think the toolbox is not working.
>  * A warning message has been solved.
>  * Draw a ROI, activate then deactivate repulsor: user looses the possibility to change the view contrast.
>  * Draw a ROI, activate repulsor, change toolbox (run `clear()` method) then click on the view -> crash.
> 
> ### Problems that are still there
>  * Activate the toolbox, draw 1 landmark, activate Repulsor, click on the view -> crash
>  * The last point fixed above does not crash anymore, however we loose the possibility to …
=> [PolygonROI] ROI/repulsor crashs and interactor problems (#807)

src/layers/legacy/medCoreLegacy/gui/toolboxes/medAbstractSelectableToolBox.cpp, src/layers/legacy/medCoreLegacy/gui/toolboxes/medAbstractSelectableToolBox.h, src/plugins/legacy/reformat/medCropToolBox.cpp, src/plugins/legacy/reformat/medCropToolBox.h, src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp, src/plugins/legacy/voiCutter/voiCutterToolBox.cpp
From PR on MUSICardio side: https://github.com/Inria-Asclepios/medInria-public/pull/782
> Fix problems/crash of:
>  * medCropToolBox crash with 4D data in workspace and pipeline.
>  * varSegToolBox block 4D data before computing.
>  * voiCutterToolBox block 4D in process and handle pipeline output.
:m:
=> [4D data] fix Cropping, Variational Seg and VoiCutter toolboxes

src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp
From PR https://github.com/Inria-Asclepios/medInria-public/pull/781 on MUSICardio side.
When using the `constructContainers` method to construct manually the containers, it needs to adjust the containers size.
:m:
=> [manualRegistration] solve top views size problem

src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
From PR https://github.com/Inria-Asclepios/medInria-public/pull/771 and https://github.com/Inria-Asclepios/medInria-public/pull/776
Correctly remove attached data at the end of Paint toolbox.
:m:
=> [Paint] Remove annotation data when destroying paint toolbox

src/plugins/legacy/polygonRoi/polygonLabel.cpp
From PR https://github.com/Inria-Asclepios/medInria-public/pull/775
> If the user draws a contour a little bit outside of the image border, he gets a very long spam of warnings in the terminal. This debugs solves the problem.
:m:
=> [PolygonRoi] avoid spam of warning if contour outside image (#775)

src/plugins/legacy/reformat/medResliceViewer.cpp, src/plugins/legacy/reformat/medResliceViewer.h, src/plugins/legacy/reformat/resliceToolBox.cpp, src/plugins/legacy/reformat/resliceToolBox.h
From PR https://github.com/Inria-Asclepios/medInria-public/pull/774 initially on MUSICardio.
> This toolbox allows to solve memory problems in Reslice toolbox: mem leaks and memory used where it was not needed.
> 
> The toolbox does not close anymore the first container to create a new one with medResliceViewer. Instead, it removes the view, change the "default widget" to medResliceViewer, then at stop it initializes the default widget and add back the original data in the container, creating a new view itself.
> Also now, changing from this toolbox to an other does not create a new container/view/etc, especially if the toolbox was not activated. Before that, even opening this toolbox with a data and switching to an other toolbox was using a lot a memory for nothing.
:m:
=> [Reslice] proper release of RAM (#774)

src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
From PR https://github.com/Inria-Asclepios/medInria-public/pull/773
> The label stayed after activating the toolbox.
=> [polygonRoi] hide activation label (#773)

src/plugins/legacy/reformat/medResliceViewer.cpp
As done in https://github.com/Inria-Asclepios/medInria-public/pull/823
This PR adds back a (background) color to display the current selected view.
This is needed for the user to choose the main orientation that is going to be used in the output data.
:m:
=> [Reslice] background color for selected view

superbuild/projects_modules/DCMTK.cmake
As in https://github.com/Inria-Asclepios/medInria-public/pull/821
The previous repo for DCMTK is down since yesterday at least. This PR switches it to the Github mirror.
:m:
=> [DCMTK] repo not accessible anymore, switch to github

src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
Fix issue https://github.com/medInria/medInria-public/issues/1190 for version 3.3.x
=> [itkDCMTKImageIO]: when getting principal axis index assume 0  for missing origin

src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
The "empty" test is quicker than "==". This PR updates the medInria3.4 branch as done on medInria3.3.
Ref:
https://github.com/medInria/medInria-public/pull/1192
https://github.com/medInria/medInria-public/pull/1202
:m:
=> [DCM] same test as on med3.3 branch, quicker

src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
From PR https://github.com/medInria/medInria-public/pull/1192 and https://github.com/medInria/medInria-public/pull/1203
Fix https://github.com/medInria/medInria-public/issues/1190 "If you try to open a DICOM in which the tag origin was not properly filled the software will crash."
:m:
=> [itkDCMTKImageIO] when getting principal axis index assume 0 for missing origin

packaging/linux/LinuxPackaging.cmake
There are various issues with CPack recompiling external projects multiple times with no optimisations, and this causes incredibly long packaging times. We can bypass the problem by installing the projects manually.
=> [Linux packaging] install external projects manually

superbuild/CMakeLists.txt
Some options are being tested before they are defined which is causing issues. It's better to have them all defined at the beginning.
=> Place superbuild options earlier

superbuild/projects_modules/DCMTK.cmake, superbuild/projects_modules/ITK.cmake, superbuild/projects_modules/LogDemons.cmake, superbuild/projects_modules/QtDCM.cmake, superbuild/projects_modules/RPI.cmake, superbuild/projects_modules/TTK.cmake, superbuild/projects_modules/VTK.cmake, superbuild/projects_modules/dtk.cmake, superbuild/projects_modules/dtkImaging.cmake
The `BUILD_ALWAYS` option is not needed unless the sources are manually modified in the project (so only for medInria). Removing it avoids unnecessary recompilations when making changes to the superbuild.
=> Remove BUILD_ALWAYS from external projects

src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp, src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.cpp, src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.h
When importing new data medInria uses the patient name, patient birthdate and study name to identify existing patients or studies. It should be using uids instead. This causes issues with data for which these fields are empty. This PR modifies the algorithm so that the patient and study uids are used in addition to the previous tags so as to handle all cases and be retrocompatible.
=> Use DICOM UIDs to identify patients and studies

src/app/medInria/medApplication.cpp, src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medDevelopmentSettingsWidget.cpp, src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medDevelopmentSettingsWidget.h
This PR adds a settings tab intended for developers.  Activating the option can make various functions and info visible in the application that would be useful for developers but confusing for normal users.
=> Add development settings

src/layers/legacy/medCoreLegacy/gui/factories/medSettingsWidgetFactory.cpp, src/layers/legacy/medCoreLegacy/gui/factories/medSettingsWidgetFactory.h
The settings tabs order is currently undefined. This may result in general settings tabs to be placed after more obscure settings added by plugins. This PR makes some changes to the settings widget factory to place the widgets in the order that they were first registered.
=> Order of settings widgets

superbuild/external_projects_tools/EP_Initialisation.cmake
The current implementation of the `ep_Initialisation` has two issues:
- It does not correctly implement arguments. The argument names (such as `USE_SYSTEM`) should not be part of the signature.
- The macro expects external projects to be cmake packages that are searchable through `find_package`.
- The macro expects the package name to be the same as the external project name.
This PR correctly implements the arguments and adds `PACKAGE_NAME` to specify alternative package names and `NO_CMAKE_PACKAGE` to allow non cmake external projects to be added. (Note that `USE_SYSTEM`, `BUILD_SHARED_LIBS` and `REQUIRED_FOR_PLUGINS` should in practice be options, not single-value arguments, but I preferred keeping the macro compatible with the current code)
_(also the `NO_CMAKE_BUILDS_PATH` option to …
=> fix ep_Initialisation macro and adapt for non-cmake projects

src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
From PR https://github.com/Inria-Asclepios/medInria-public/pull/812
> If you open the polygonROI toolbox, add a data, draw something, then click on the button to deactivate the toolbox, the ROI is still displayed, even if you change the slice, even if you switch to another toolbox.
> This PR clears properly the toolbox/view if we deactivate it.
:m:
=> [PolygonRoi] clear deactivating the tlbx

src/app/medInria/main.cpp, src/app/medInria/medMainWindow.cpp, src/app/medInria/medMainWindow.h, src/layers/medCore/parameter/medStringParameter.cpp, src/layers/medCoreGui/notification/widgets/medNotifWindow.cpp, src/layers/medCoreGui/notification/widgets/medNotifWindow.h, src/layers/medCoreGui/parameter/medStringParameterPresenter.cpp, src/layers/medCoreGui/source/medDataHubPresenter.cpp, src/layers/medCoreGui/source/medSourceModelPresenter.cpp, src/layers/medCoreGui/source/settings/widgets/medSourceSettingsWidget.cpp, src/layers/medCoreGui/source/settings/widgets/medSourcesSettings.cpp, src/layers/medCoreGui/source/settings/widgets/medSourcesSettings.h, src/layers/medCoreGui/source/settings/widgets/medSourcesSettingsHandlerWidget.cpp, src/layers/medCoreGui/source/widgets/medSourcesItemDelegate.cpp
- medSourcesItemDelegate : fixed segmentation fault error caused by protocol change with medPACS plugin 
- medSourcesSettings et medSourcesSettingsHandlerWidget : added a signal for the creation of a first instance of any plugin to activate the 'connect' button display
- medSourceSettingsWidget : fixed segmentation fault caused by deleting all plugin instances
- medSourceModelPresenter and medDataHubPresenter : fixed problem displaying a newly created instance in the Browser: list of instances + display of instance data
- medStringParameterPresenter : change the dialog window name of buildLineEditFileImport to make this representation a case for reuse
- medStringParameter : change the medStringParameter cursor position to remain at the position of the last modification
- medMainWindow, …
=> debug medInria core

RELEASE_NOTES.txt
Due to changes in anima plugins management, and waiting for futur changes in medInria 4 changing the way plugins are handled, Anima plugins are temporarily removed from medInria.
This PR adds a mention about it in the release notes.
:m:
=> [Release3.4] add info about Anima plugins in release notes

src/plugins/process/morphomath_operation/CMakeLists.txt
In order to compile dev branch on macOS and Windows (with VS 2022), we need to add the right ITK module in morphomath_operation plugin.
=> [Compilation] morphomath_operation ITK modules

src/layers/medCoreGui/notification/widgets/medNotifWindow.cpp, src/plugins/legacy/medShanoir/internal/Levels.h
When the notification popup fades out it is not destroyed. This prevents the user from using the mouse on the area where the popup is still present (but invisible).
(I also fixed a minor compilation issue I encountered while testing testing bug)
=> Notification widget bug and minor compilation issue

src/plugins/legacy/reformat/medResliceViewer.cpp
Same as https://github.com/medInria/medInria-public/pull/1207 on medInria3.4.x
This PR adds back a (background) color to display the current selected view.
This is needed for the user to choose the main orientation that is going to be used in the output data.
:m:
=> [Reslice] background color for selected view --dev

src/layers/legacy/medVtkInria/vtkImageView/vtkImageViewCornerAnnotation.cxx, src/layers/legacy/medVtkInria/vtkWidgetsAddOn/vtkOrientationAnnotation.cxx, src/layers/legacy/medVtkInria/vtkWidgetsAddOn/vtkOrientationAnnotation.h
On dev branch of medInria, the orientation annotation in center of view borders are not well displayed.
Since newer version of VTK, `vtkCornerAnnotation::SetTextActorsPosition` method takes a `const` value, and if we don't change also in medInria, our virtual `vtkOrientationAnnotation::SetTextActorsPosition` method is not called.
:m:
=> [Annotation] fix A/R/P/L orientation annotations in views

RELEASE_NOTES.txt, src/plugins/legacy/LCCLogDemons/LCCLogDemons.cpp, src/plugins/legacy/LCCLogDemons/LCCLogDemons.h, src/plugins/legacy/LCCLogDemons/LCCLogDemonsToolBox.cpp, src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.cpp, src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.h, src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp, src/plugins/legacy/manualRegistration/manualRegistration.cpp, src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp
From PR https://github.com/Inria-Asclepios/medInria-public/pull/861 on MUSICardio.
This PR enhances the Registration workspace:
* LCC Log Demons and Diffeomorphic cast data before registering, instead of blocking if the inputs were not the same size, spacing, etc.
* Manual Registration: users were not seeing so much the landmark number, this PR enhance the design of the text.
:m:
=> [Registration] cast data in LCC and Diffeo, enhance txt in Manual

src/app/medInria/medLogger.cpp
Same as medLogger commits from https://github.com/medInria/medInria-public/pull/1117
Solves several memory leaks in medLogger from teestreams, teedevices and d.
:m:
=> [MemoryLeak] medLogger TeeStreams, TeeDevices and d -- dev

src/layers/legacy/medVtkInria/vtkWidgetsAddOn/vtkImageOrientedPointWidget.cxx, src/layers/legacy/medVtkInria/vtkWidgetsAddOn/vtkImageOrientedPointWidget.h, superbuild/projects_modules/VTK.cmake
VTK 9.2.6 was not adapted to compile on Ubuntu 24. Version 9.3.1 is ok.
edit: PR compiles on Ubuntu 22 too
:m:
=> [VTK9.3.1] compilation for Ubuntu 24

src/layers/medCore/legacy/data/medAbstractData.cpp, src/layers/medCore/legacy/parameters/medParameterPoolManagerL.cpp, src/layers/medCore/legacy/parameters/medParameterPoolManagerL.h, src/layers/medCore/legacy/parameters/medTimeLineParameterL.cpp, src/plugins/legacy/medVtkView/medVtkView.cpp
Same as https://github.com/medInria/medInria-public/pull/1124
"Fix a memory leak building the thumbnail importing a data. This PR removes the need to resize a pop-up to get a thumbnail with the right size. Instead, we resize a QImage."
:m:
=> [MemoryLeak] medVtkView::buildThumbnail -- master

src/plugins/legacy/itkDataImage/writers/itkMetaDataImageWriter.cpp
On master branch, "mha" was missing from supported file extensions to export data. Only mhd. This PR adds back mha, as on medInria3.4.x branch.
:m:
=> [mha] put back mha with mhd by default exporting data

src/layers/legacy/medVtkInria/vtkImageView/vtkImage2DDisplay.cpp, src/layers/legacy/medVtkInria/vtkImageView/vtkImage3DDisplay.cpp
Same as https://github.com/medInria/medInria-public/pull/1151 on master branch.
m_sVtkImageInfo is a complex structure with constructor and destructor, and should not be reset with memset.
:m:
=> [medVtkImageInfo] proper reset of a complex structure -- master

src/layers/legacy/medVtkInria/vtkWidgetsAddOn/vtkImageOrientedPointWidget.cxx, src/layers/legacy/medVtkInria/vtkWidgetsAddOn/vtkImageOrientedPointWidget.h
Following https://github.com/medInria/medInria-public/pull/1246
Debug windows compilation, due to VTK 9.3.1. Use of modern "SetViewProp" method.
:m:
=> [vtkImageOrientedPointWidget] switch to modern vtk 9.3.1 use for windows

src/app/medInria/medApplication.cpp, src/app/medInria/medApplication.h, src/app/medInria/medMainWindow.cpp
Put back the old splashscreen behavior: 
* do not show on debug mode
* display at the previous screen used by the application
* also a small debug: save the current screen even if the app is in fullscreen
:m:
=> [SplashScreen] display the splashscreen on right screen and in release only

superbuild/projects_modules/medInria.cmake
Fix https://github.com/medInria/medInria-public/issues/1261 a compilation error on Ubuntu and Fedora with the installation prefix.
From a work with @Florent2305 
:m:
=> [Ub/Fedora] compilation medInria install prefix
